Xeeynamo/sotn-decomp

src/st/no3/377D4.c

in NO3, matched this 7 functions:
- func_801BE9F4
- func_801C4F64
- func_801C4FA0
- func_801C55E8
- func_801C5620
- func_801C5794
- func_801C57C4

work for today

---

src/st/no3/377D4.c

refactors a few goto loops to be while (true) loops instead

refactor a few 377D4 funcs

---

Makefile
tools/find_duplicates.py

i had to edit the make file also to tell ld to generate .map files

find_duplicate.py tool, credit to Ethan and papermario decomp team

---

src/st/cen/D600.c

used the dupes tool to spot the low hanging fruit in CEN

[CEN] cleared obvious duplicates

---

include/dra.h
include/unkstruct.h
src/dra/42398.c

Decompile func_800E9610

---

src/dra/42398.c

Not totally sure how to fix the `(*(var_v1 - 5))` part, open to suggestions there.

 Decompile func_8011BD48 

---

tools/find_duplicates.py

this should make the order of the function deterministic

[Tool] sort by overlay first and function name

---

src/st/st0/2C564.c

I'm giving up on this one for the time being, and  since it's almost complete, i'm leaving the scratch so it doesn't get lost in the 7th dimension.
https://decomp.me/scratch/kUpoj

EntityDraculaFinalForm Scratch

---

Makefile

A few tweaks to the Makefile:
* `PSXCC_FLAGS` now contains all the GCC flags that only work with the old versions
* Add debug symbols in the PSX ELFs by adding `-g` and by removing `-s`
* Remove `--no-check-sections` as the reallocation would break the executable if we add too much data
I did not remove `-s` from the Saturn version. We might want to do that but we also need to add the `-g` flag in `tools/saturn-splitter/scripts/compile_dosemu/compile_dosemu.sh` (cc. @sozud)

Do not strip debug symbols and start to support modern GCC

---

Makefile
config/saturn/game_user_syms.txt
src/saturn/game.c
src/saturn/game.h
src/saturn/sattypes.h

Co-authored-by: Luciano Ciccariello <Xeeynamo@users.noreply.github.com>

Decompile func_060705CC

---

config/saturn/zero_user_syms.txt
src/saturn/lib/def.h
src/saturn/lib/mth.h
src/saturn/lib/scl.c
src/saturn/lib/scl.h
src/saturn/lib/spr.h
src/saturn/lib/sys.h
src/saturn/lib/xpt.h
src/saturn/sattypes.h

I renamed Fixed32 to SotnFixed32  due to name conflicts.

Add more SCL

---

.github/workflows/saturn-build.yml
.github/workflows/validate-and-report.yml
tools/function_finder/function_finder_psx.py
tools/function_finder/function_finder_saturn.py
tools/function_finder/helpers.py

Merges some code between the PSX and the Saturn function finders. The only functional change is the PSX function finder now exports in markdown. This is to prepare the integration of #396 in the CI.

Function finder refactoring

---

include/entity.h
src/st/nz0/30958.c

This fixes up func_801B3C38 to PR guidelines regarding usage of ext and stub as discussed in https://github.com/Xeeynamo/sotn-decomp/pull/401#issuecomment-1656491828

Fix func_801B3C38

---

include/game.h
src/dra/5298C.c
src/dra/5D6C4.c
src/dra/demo.c
src/st/dre/14774.c
src/st/mad/D8C8.c
src/st/no3/3FF00.c
src/st/np3/390BC.c
src/st/nz0/36DE4.c
src/st/st0/30030.c
src/st/wrp/6FD0.c
tools/lints/relics.py

This adds a script to fix relic magic numbers and applies it.

Relic documentation and linter

---

tools/analyze_calls.py

Two major changes here:
Running `python3 analyze_calls.py ALL_DRY` will do a "dry run" of generating all the call graphs. It will generate sotn_calltree.txt, and then it will generate all the SVG files, but crucially they will not be saved to .svg, they will just be generated and then forgotten. No HTML file will be generated. Then, sotn_calltree.txt will be deleted.
All known failure states for the tool now use exit(#) with different exit codes depending on the type of failure. This should make it easier for the CI to detect problems.
Note that this PR only allows analyze_calls to do the dry run - it does not include the actual workflow modifications that would be needed to actually do the dry-run.

Add dry run capability to analyze_calls for PRs

---

include/game.h
src/dra/5D6C4.c

This does the refactor suggested here https://github.com/Xeeynamo/sotn-decomp/pull/411#issuecomment-1657267022
I'm pretty sure this is correct based on GetEquipOrder and GetEquipCount https://github.com/Xeeynamo/sotn-decomp/blob/6050bb51542257efaa660f8d46380a6b9dd6df36/src/dra/5D6C4.c#L44
This is just the refactoring part and not the labeling.

Items refactor

---

src/st/cen/10E4C.c
src/st/dre/16F90.c
src/st/no3/4184C.c
src/st/np3/390BC.c
src/st/nz0/394D4.c
src/st/rwrp/A168.c
src/st/st0/3186C.c
src/st/update_stage_entities.h
src/st/wrp/81E8.c

This skips MAD again since I don't seem to be able to use config/symbols.stmad.txt to set the addresses of things.

Decompile UpdateStageEntities

---

include/psxsdk/libgte.h
src/st/np3/3246C.c
src/st/np3/np3.h

First function in the project to use GTE functions i think, i had a hard time with the loop near the end and the types, i cleaned it up the best i could.
I'm leaving the scratch here in case somebody wants to mess with it and maybe get to remove the padding i had to use for the stack pointer:
https://decomp.me/scratch/s3BEy

NP3 func_801B3704

---

config/symbols.us.stcen.txt
config/symbols.us.stdre.txt
config/symbols.us.stno3.txt
config/symbols.us.stnp3.txt
config/symbols.us.stnz0.txt
config/symbols.us.strwrp.txt
config/symbols.us.stst0.txt
config/symbols.us.stwrp.txt
src/st/cen/11280.c
src/st/cen/1B274.c
src/st/dre/1C7DC.c
src/st/no3/46684.c
src/st/no3/564B0.c
src/st/np3/3DEF4.c
src/st/np3/4E69C.c
src/st/nz0/48ADC.c
src/st/nz0/49930.c
src/st/rwrp/A59C.c
src/st/st0/2B0C8.c
src/st/st0/2C564.c
src/st/st0/36358.c
src/st/unk_loop_func.h
src/st/wrp/D020.c

I'm open to ideas on the name.

De-duplicate UnkLoopFunc

---

config/splat.us.stnp3.yaml
src/st/np3/3246C.c
src/st/np3/365FC.c
src/st/np3/np3.h

https://decomp.me/scratch/SWjQq

NO3 func_801B65FC

---

config/symbols.us.stnz0.txt
include/entity.h
src/st/nz0/4672C.c
src/st/nz0/nz0.h

Seems to be the last function the Spittlebone was missing for it's file to be complete.
https://decomp.me/scratch/hAalp

NZO EntityRotateSpittlebone

---

src/dra/8D3E8.c

Yet another function. Interesting that it keeps making use of D_80072BD0. Hopefully once this whole function family is in we can piece together how they are meant to work together.

Decompile DRA func_8012E550

---

config/splat.hd.dra.yaml
config/splat.us.dra.yaml
src/dra/72BB0.c

This has a lot of similarities to my previous PR. Otherwise, not a ton of interesting content here.
This does appear to be the final function in 72BB0.c, which is nice.

Decompile DRA func_801131C4

---

include/memcard.h
src/st/sel/2C048.c
src/st/sel/2D260.c
src/st/sel/sel.h

A very old non matching that took me two mintues to decompile. Just to save me the frustration from another function I can't get right.
I had some minor refactoring lying down in the list of changes yet to submit. I decided to include them in this PR. They are very minor changes, it should be okay.

SEL DrawString16x16

---

src/weapon/w_022.c

The next least-complex one of these. This one is for the Magic Missile. Kind of neat to be able to recognize the behavior. This definitely seems like the logic for the missile itself, since it moves at a fixed X speed until it has a hit flag, at which point it changes its AnimationFrame, changes its `step` to 2, and then lets its animation run out and destroys itself.

Decompile w_022 func_ptr_80170004

---

src/st/sel/2D260.c

Thanks to @bismurphy for suggesting how to match this

SEL func_801AD66C

---

Makefile
config/saturn/zero_user_syms.txt
src/saturn/zero.c
src/saturn/zero.h

I removed the stripping so these can be loaded into Ghidra with symbols.

Saturn: Decompile entrypoint, don't strip elfs

---

src/dra/5298C.c
src/dra/dra.h

This function seems to be related on how to display certain menu graphics. The only affected visual element I saw is the preview icon at the bottom right in the Equip sub-menu. I was not able to identify how this function fits in the grand scheme, therefore I did not find any suitable name.

DRA func_800F84CC

---

src/ric/345EC.c
src/ric/ric.h

Small helper function used by func_8017091C which was merged in #820.
Not really sure what it does but it's something with angles and it uses recursion which is kind of unusual.

Decompile RIC func_80170C60

---

config/splat.us.ric.yaml
include/entity.h
src/ric/345EC.c
src/ric/ric.h

Another entity function in RIC, continuing to work through these to remove the rodata padding.
Still no knowledge of what this function is for but once I get these done I'll focus on getting the entity factory system working in RIC like we have it in DRA, I've found a lot of the important functions already.

Decompile RIC func_80170F64

---

include/entity.h
src/ric/345EC.c

And yet another Richter entity function :)
No further comments, just continuing through this file. This one doesn't have rodata but it's sandwiched in between the others so might as well finish it off.

Decompile RIC func_8017161C

---

config/splat.us.ric.yaml
include/entity.h
include/game.h
include/types.h
src/ric/345EC.c
src/ric/ric.h

This is a pretty big function, and I'll admit that my code for it is pretty low quality. But it matches. Scratch is here if you'd like to make improvements:
https://decomp.me/scratch/xok2Z
A lot of the things that I tried to remove the gotos and temp variables didn't work.
The entity extension for this uses f32 variables. Those are defined in `game.h`, but `game.h` is not accessible to `entity.h`, so I moved the definition of f32 to `types.h` which is accessible in all places and overall seems like a better place for it anyway.

Decompile RIC func_801719A4

---

src/st/rwrp/14590.c

Decompile dupe function rwrp func_801A2550

---

src/main/psxsdk/libsnd/libsnd_internal.h
src/main/psxsdk/libsnd/scssvol.c
src/main/psxsdk/libsnd/vmanager.c
src/main/psxsdk/libspu/libspu_internal.h
src/main/psxsdk/libspu/s_stm.c

libsnd libspu funcs

---

config/symbols.us.ric.txt
src/ric/1AC60.c
src/ric/21250.c
src/ric/ric.h

Richter's other special move, I think these are the only two.
Very weird logic in the initialization (everything above the switch), but I got a match.

Decompile RIC CheckBladeDashInput

---

src/ric/1AC60.c

Just the next sequential function, this one is fairly simple. No real comments to share beyond that.

Decompile RIC func_8015A7D0

---

src/dra/75F54.c
src/ric/22380.c
src/ric/ric.h

99% copied from DRA func_80119F70, but cannot be deduped due to subtle differences.

Decompile RIC func_8015FEA8

---

config/splat.us.ric.yaml
src/ric/24788.c
src/ric/ric.h

Similar to an existing DRA function, which is noted.

Decompile RIC func_8016147C

---

config/symbols.hd.dra.txt
config/symbols.us.ric.txt
include/entity.h
src/dra/86ECC.c
src/ric/345EC.c

Realized this matches a function in RIC, so this PR decompiles the DRA version, and also renames the RIC version to match.

Decompile DRA EntityStopWatchExpandingCircle

---

src/dra/7A4D0.c
src/dra/dra.h

I was casually browsing this file and I found some potential improvements for this function.

Fix func_8011A870

---

config/symbols.us.stnp3.txt
src/st/adjust_value_within_threshold.h
src/st/cen/11280.c
src/st/dre/173C4.c
src/st/mad/EDB8.c
src/st/no3/41C80.c
src/st/np3/394F0.c
src/st/nz0/39908.c
src/st/rwrp/A59C.c
src/st/st0/31CA0.c
src/st/wrp/861C.c

Credit to ChatGPT for helping my ape brain ﻿understand what this function actually does...

Dedupe AdjustValueWithinThreshold

---

include/game.h
src/st/sel/3410C.c

One annoying `do { } while (0);` left but it matches.﻿

Decompile SEL func_801B519C

---

config/splat.us.stdre.yaml
include/game.h
src/st/dre/22848.c

While looking into understanding the scratchpad, I ended up decompiling this function.

DRE func_801A2C9C

---

src/dra/843B0.c
src/ric/2A060.c

Exact copy (aside from using g_api) of an existing DRA function. It was not obvious that these would match, and took a lot of digging to work out that they were the same, but I'm glad I went through that process, because otherwise decompiling this would be annoying! Definitely will be important to keep doing that as we go forward. It's amazing how much of RIC and DRA are similar.

Decompile RIC func_801682B4

---

config/symbols.us.dra.txt
src/ric/21250.c
src/ric/2C4C4.c
src/ric/ric.h

Did the DRA version of this a while ago, now here is RIC. Very little overlap, generally speaking, which kind of surprises me. Anyway, more progress on RIC!

Decompile RIC EntitySubwpnCrashCrossParticles

---

include/entity.h
src/ric/21250.c
src/ric/2C4C4.c
src/ric/ric.h

Huge amount of similarity with the Agunea crash, which is interesting. Otherwise, nothing more to say from my end!

Decompile RIC EntitySubwpnCrashAxe

---

src/ric/21250.c
src/ric/2C4C4.c
src/ric/ric.h

Another one that is similar to, but subtly different from, the DRA version. Might be interesting to do a diff between these corresponding functions sometime to fully describe the differences between Richter and Alucard's behavior.

Decompile RIC EntitySubwpnThrownVibhuti

---

config/splat.us.ric.yaml
src/dra/7A4D0.c
src/dra/86ECC.c
src/dra/dra.h
src/ric/21250.c
src/ric/2C4C4.c
src/ric/ric.h

Another one very similar to a DRA function.
Noticed the DRA one still had a placeholder `func_` name so I've also renamed that.

Decompile RIC EntitySubpwnAgunea

---

config/symbols.us.dra.txt
config/symbols.us.ric.txt
include/entity.h
src/dra/7A4D0.c
src/dra/86ECC.c
src/dra/dra.h
src/ric/21250.c
src/ric/2C4C4.c
src/ric/ric.h

This one was pretty complicated but I'm glad I got it working. Not completely certain what this does but good enough for now. The two functions are even more similar than DRA and RIC functions usually are.
For any comments to be made, feel free to only comment on one of the two instances and I will make the change on both.

Decompile DRA and RIC EntityAguneaHitEnemy

---

config/splat.us.ric.yaml
include/entity.h
include/primitive.h
src/ric/2C4C4.c
src/ric/319C4.c
src/ric/ric.h

Required splitting to a new file.
Yet another instance of PRIM_LINE_G2 using its own type of Primitive, which is neat.
Also resolved another member of that primitive. This is getting wild! RIC is so close!

Decompile RIC func_8016D9C4

---

include/entity.h
src/ric/319C4.c

Big thanks to @mkst for the final bits on this one!

Decompile RIC func_8016E46C

---

tools/analyze_calls.py

Note that this is a PR into the renderentities branch, not into master.
This seems to be an acceptable fix for now.

bandaid fix for analyze_calls issue in renderentities PR

---

src/st/st0/2C564.c

A strange function that does things with manipulating pixel colors. Luckily I found ClutLerp which I was able to take inspiration from. Still a weird function and I don't really understand how it works, but thankfully it matches. This was a very "fragile" one, where the tiniest change would break everything and I was surprised when suddenly I got a purple checkmark.
Here is the scratch if interested. https://decomp.me/scratch/G9e8f

Decompile ST0 func_801ADB10

---

src/main/psxsdk/libsnd/libsnd_internal.h
src/main/psxsdk/libsnd/seqread.c
src/main/psxsdk/libsnd/vmanager.c

https://decomp.me/scratch/1fFBT
https://decomp.me/scratch/D19VS
https://decomp.me/scratch/5vgQZ

SsUtChangePitch

---

include/entity.h
src/st/st0/2C564.c
src/st/st0/st0.h

This is some sort of helper function, called by the entity func_801AF774 (not yet decompiled).
It's kind of a mess, but unfortunately everything I tried to make it pretty broke the match in subtle ways.
Because it is only called by one entity, I make a new Ext member for that entity, since this plays with prims in the Ext section. I will next proceed toward decompiling that entity, which will likely involve making a more complete Ext entry.

Decompile ST0 func_801AF380

---

.github/workflows/format.yml
.github/workflows/linter.yaml
.github/workflows/picci.yaml
.github/workflows/saturn-build.yml
.github/workflows/tool-debugmodule.yaml
.github/workflows/validate-and-report.yml

I noticed a few deprecation warnings so went through and updated all the "uses" dependencies to the latest.

Bump CI deps

---

src/pc/psxsdk/libgte.c

I verified with a PS1 emulator the values

ratan2, SquareRoot0, SquareRoot12

---

config/splat.us.weapon.yaml
src/weapon/w_010.c
src/weapon/w_026.c
src/weapon/w_027.c

this is a step along the way to getting splat updated, but im not there yet :)

weapon rodata migration

---

src/main/psxsdk/libsnd/libsnd_i.h
src/main/psxsdk/libsnd/next.c
src/main/psxsdk/libsnd/seqread.c

Thanks to an anonymous person who fixed this scratch https://decomp.me/scratch/Aw4jQ

_SsGetMetaEvent

---

config/symbols.us.dra.txt
src/dra/5087C.c
src/pc/stubs.c

A relatively small but complicated function. I matched it by decompiling from scratch while taking some inspiration from an old scratch made by @sonicdcer

DRA func_800F24F4

---

src/weapon/w_045.c

If the control flow on this could be better, let me know.

Decompile w_045's func_13F000_8017A718

---

src/main/psxsdk/libsnd/libsnd_i.h
src/main/psxsdk/libsnd/vmanager.c
src/main/psxsdk/libspu/s_si.c

Not sure what the deal is with this line:
```
if ((u16)_svm_voice[voice].unke == (u16)temp) {
```
changing unke to unsigned causes a mismatch in SpuVmInit

SpuVmSetSeqVol

---

config/splat.us.main.yaml
include/psxsdk/libetc.h
src/main/psxsdk/libapi/l10.c
src/main/psxsdk/libetc/intr.c

Correct the split of libapi/l10.c and decompile few trivial functions in it.

Correct the split of libapi/l10.c

---

src/main/psxsdk/libsnd/decre.c
src/main/psxsdk/libsnd/libsnd_i.h

Thanks to @dezgeg @mkst @Xeeynamo

_SsSndDecrescendo

---

src/main/psxsdk/libsnd/seqinit.c

https://decomp.me/scratch/mQesq

_SsInitSoundSeq

---

config/splat.us.stwrp.yaml
config/symbols.us.stwrp.txt
include/game.h
src/st/wrp/6FD0.c
src/st/wrp/73A0.c
src/st/wrp/entity_heart_drop.c
src/st/wrp/wrp.h

About time... Got the match thanks to the [PSP counterpart](https://decomp.me/scratch/HGaVX).

WRP EntityWarpRoom

---

src/weapon/w_037.c

Not completely clear what this one does, but we'll work it out someday.
Thank you to xeeynamo and sozud for finishing the match on this one :)

Decompile Weapon 37 helper 8017B0AC

---

include/entity.h
src/weapon/w_021.c

A couple of the entity fields were different for this compared to the existing ET_Weapon, so I made a special one for food.

Decompile EntityWeaponAttack for Weapon 21 (food)

---

src/weapon/w_037.c

My last PR for the moment; we've burned through my backlog :) No other real comments to share.

Decompile Weapon 37 func_ptr_80170004

---

src/main/psxsdk/libapi/counter.c

https://decomp.me/scratch/jawso

Implement SetRCnt

---

src/weapon/w_023.c

Looks like just another weapon function.
Weird uses of the Weapon struct. Unfortunately Weapons don't seem to have any consistency among them. Would be nice if we could define the Entity extension in each weapon's `w_0XX.c` file, but I don't think that's a possibility in C.

Decompile weapon 23 func_ptr_80170028

---

config/symbols.pspeu.dra.txt
src/dra_psp/4370.c

RenderPrimitives https://decomp.me/scratch/OvTcA
func_800EDD9C https://decomp.me/scratch/xYX6N

psp dra syms

---

src/st/wrp_psp/prim_helpers.c

I created Primitive2 to avoid doing a big refactor. Not sure how correct the struct definition is or not but putting it up for comments.
https://decomp.me/scratch/DzATf

PrimDecreaseBrightness

---

src/st/cen/18084.c
src/st/clut_lerp.h
src/st/dre/1E1C8.c
src/st/mad/15520.c
src/st/no3/48A84.c
src/st/np3/402F4.c
src/st/nz0/4070C.c
src/st/rwrp/113A0.c
src/st/st0/36358.c
src/st/wrp/e_misc.c

Another de-duplication done using my automated script. Still finding some bugs, but these results are promising. The process becomes an absolute breeze.

De-duplicate ClutLerp

---

src/st/wrp_psp/popup.c

Seems to use a different character encoding on PSP.
https://decomp.me/scratch/OZfBf

BottomCornerText

---

src/weapon/w_027.c

Noticing a lot of similarity among the shield spells. Not enough to de-duplicate them, but enough that decompiling them is a breeze.
Unless there is something else that takes my attention, I will probably focus on decompiling all the shields next. I'm already done with 2 and there aren't many in the game.

Decompile W27 (Medusa Shield) EntityWeaponShieldSpell

---

src/weapon/w_027.c

Started working on this one and then I realized it's identical to the one on the previous shield, so it was a direct copy-paste, aside from the names of the D_C1000 variables.
Maybe we'll de-duplicate in the future but for now I think weapons should just be written individually.

Decompile Weapon 27 EntityWeaponAttack

---

include/unkstruct.h
src/dra/692E8.c
src/dra/71830.c
src/dra/75F54.c
src/dra/8D3E8.c

This is a collision function, similar to the ones that were completed for Richter a little while ago.
I changed the collision offsets to use Point16, instead of the old s16_pair struct.

Decompile DRA func_8010C36C

---

src/dra/692E8.c
src/dra/75F54.c
src/dra/8D3E8.c
src/dra/dra.h
src/pc/stubs.c

The second in that set of 4 player collision functions.
I also changed D_800ACEC0 to be Point16 instead of s16_pair.

Decompile DRA func_8010C9F4

---

include/unkstruct.h
src/dra/692E8.c
src/dra/71830.c
src/dra/75F54.c
src/dra/7A4D0.c
src/dra/8D3E8.c
src/dra/dra.h
src/pc/stubs.c

The next one! And yet another renaming struct to Point16.
Almost done!

Decompile DRA func_8010D010

---

src/dra/692E8.c

Last one of the set! Cool to have gotten this all done in one night :)
Excited to see the results once the 80109A44 function comes in from xeeynamo!

Decompile DRA func_8010D2C8

---

src/dra/4A538.c
src/pc/stubs.c

https://decomp.me/scratch/lSGji
Credit to @Xeeynamo for 99% of the initial match, I just fixed up one of the registers and did some light refactoring. The repetition of `temp_s0 = ptr->desc` makes me think it's actually an array reference but I couldn't get anything else to fit.

Decompile DRA func_800EA7CC

---

include/entity.h
src/weapon/w_026.c

Kind of a crazy one with the way the vectors are dealt with, but eventually got it to work. Hopefully this can be a nice reference for some of those SDK functions.

Decompile weapon 26 func_ptr_80170024

---

include/common.h
include/game.h
src/st/dre/22848.c

Kind of a messy function to match, but it matches. Looks like there are a few functions in this file with similar structure.

Decompile DRE func_801A2848

---

CMakeLists.txt
include/game.h
src/pc/pl_arc.c
src/pc/sim_pc.c
src/pc/sotn.c
src/pc/stages/stage_dummy.c
src/pc/stubs.c

And it does not crash any more.
trust me bro

Add Alucard sprite support

---

src/st/dre/22848.c

Thank you to @hohle for solving the last line swap mismatch!
This is the last of the dependencies for DRE Entity3DBackgroundHouse, so hopefully that one will be doable now. I'll get started on it :)

Decompile DRE func_801A2A58

---

config/splat.us.stdre.yaml
include/entity.h
src/st/dre/22848.c

This one was fun! Lots of use of the coordinate transformation functions, and lots of weirdly packed data.
Had to shift the splat a little bit. This is the last function in the file (location-wise, not the last to be decompiled) and the end of the C segment was slightly off.

Decompile DRE Entity3DBackgroundHouse

---

include/primitive.h
include/unkstruct.h
src/st/nz0/43F9C.c

This is an old function which is decompiled, but is messy. It had an Unkstruct, which I determined to be a variant of the Primitive. Therefore, we add a new Primitive version to Primitive.h, and delete the Unkstruct, rewriting this function.
Hopefully decompiling the caller will help to determine what this function does, as well as what the unknown primitive members are.

Improve NZ0 func_801C3F9C

---

include/types.h
src/pc/psxsdk/libgte.c
src/st/wrp/e_misc.c

One of the last two functions!
Since this is duplicated in every overlay (but never used in any of them), it will make sense to de-duplicate this. I will use my automatic de-duplication script to put it into the appropriate .h file. That can either be in this PR (after getting the seal of approval), or can be a separate PR (after merging this initial WRP version). I'm good with any option.
Very cool though, glad I figured this one out finally! Hopefully the last one will come along soon...

Decompile WRP func_801907EC (!)

---

config/symbols.stmad.txt
config/symbols.us.stcen.txt
config/symbols.us.stdre.txt
config/symbols.us.stno3.txt
config/symbols.us.stnp3.txt
config/symbols.us.stnz0.txt
config/symbols.us.strwrp.txt
config/symbols.us.stst0.txt
src/st/cen/18084.c
src/st/dre/1E1C8.c
src/st/mad/15520.c
src/st/no3/48A84.c
src/st/np3/402F4.c
src/st/nz0/4070C.c
src/st/rwrp/113A0.c
src/st/st0/36358.c
src/st/unk_recursive_primfunc_1.h
src/st/wrp/e_misc.c

Fairly straightforward de-duplication. If anyone has better names for either the function or the array it uses, feel free to suggest them, but with this thing being so weird and its purpose being unknown, I had to keep the names pretty generic.

De-duplicate the first of the recursive prim functions

---

config/splat.us.stnp3.yaml
config/symbols.hd.dra.txt
src/st/np3/4E69C.c
src/st/np3/4F5B8.c
src/st/np3/np3.h

Next one in the sequence, nothing much additional to share.

Decompile NP3 EntityGurkhaBodyParts

---

config/splat.us.stnp3.yaml
src/st/np3/4F5B8.c

The last one I have ready for this set. Should be a nice chunk of NP3 to knock out!

Decompile NP3 EntityGurkha

---

config/splat.us.stnp3.yaml
config/symbols.us.stnp3.txt
include/entity.h
src/st/np3/4B018.c
src/st/np3/4BF18.c
src/st/np3/np3.h

Another big one! This required mangling the files a little bit; once the other functions are decompiled the files should come back together nicely. The function itself is in 4B018.c, and the function is currently alone in that file.

Decompile NP3 EntityOwl

---

config/symbols.us.stnp3.txt
src/st/np3/4BF18.c
src/st/np3/np3.h

Helper function for the Owl Knight, does a bunch of stuff with prims. Might be related to his death animation.

Decompile NP3 func_801CBF18

---

config/symbols.us.main.txt
include/game.h
src/main/main.c

Decompile main

---

config/splat.us.stnp3.yaml
src/st/np3/402F4.c
src/st/np3/44144.c

This is a helper function for the entity that comes right after it.
It's relatively simple in terms of functionality, but I have no idea what it's actually doing, so unfortunately everything is completely unnamed. At least it matches.

Decompile NP3 func_801C4144

---

src/st/st0/30030.c
src/st/wrp/bss.c

Minor fake symbols fix

---

config/symbols.hd.dra.txt
config/symbols.us.dra.txt
src/dra/843B0.c
src/pc/stubs.c

Shout out to @bismurphy for doing most of the initial work on this match.
PSX:  https://decomp.me/scratch/2GysU
PSP: https://decomp.me/scratch/cjmbN

Decompile DRA EntitySubwpnThrownDagger

---

include/entity.h
src/weapon/w_013.c

Finishes the heaven sword.
More weirdness with the ext - it appears that unk84 is used differently in different functions within this value.
Overall, this file could use some improvements, but to start out, having it decompiled is better than not. Hopefully someone can figure out how this actually all works.

Decompile heaven sword EntityWeaponAttack

---

include/entity.h
src/weapon/w_020.c

Decided to target this one since it's the largest remaining function in `weapon` and now it's done. Kind of surprising that such a simple weapon has such a huge function, but I guess it has a lot of graphics and therefore a lot of primitive manipulation.

Decompile Karma Coin EntityWeaponAttack

---

config/splat.us.dra.yaml
src/dra/692E8.c
src/dra/6D59C.c
src/dra/71830.c
src/dra/72BB0.c
src/dra/75F54.c
src/dra/7A4D0.c
src/dra/843B0.c
src/dra/8D3E8.c
src/dra/dra.h
src/pc/stubs.c
src/ric/1AC60.c
src/ric/1FCD0.c

There was a question in the decomp discord about the bounce when Alucard dive-kicks and hits an enemy. I tracked this down, and in the process, found some moderately old functions that could use some improvements to their code style. I also cross-referenced these with PSP to make the code make a bit more sense.
The PSP version makes it clear that D_800ACF7C is not a struct and is just an array of s16, so I made that change. The struct version matched on PS1, but now that PSP reveals that it was fake, we turn it back to just an array.
Let me know if I missed anything! Nice to have real names for some of these functions.

Refactor/clean-up of some of Alucard's jumping logic

---

src/dra/7A4D0.c

See commit messages for details.

Fix match with latest maspsx and update it

---

tools/sotn-debugmodule/debugmode.c
tools/sotn-debugmodule/flag_checker.c

Changing to deconflict with wolf transform button.

Change debug button to L2

---

Makefile
src/main/psxsdk/libgpu/sys.c

This file seems to use an older aspsx. Thanks to @mkst for the fixes

More libgpu, maspsx update

---

src/st/init_entity.h
src/st/mad/11D3C.c
src/st/nz0/3C8EC.c
src/st/rwrp/D580.c
src/st/wrp/st_common.c

Update `InitializeEntity` to use the PSP decompilation and remove duplicate implmeentations across stages.

Use PSP InitializeEntity Impl

---

src/pc/sdl2.c

Implement PadInit

---

src/st/no3/48A84.c

https://decomp.me/scratch/inbZb

Decompile NO3 func_801CE740

---

include/entity.h
src/weapon/w_058.c

Finishing the Alucart Shield.
Noticed we are doing stuff with offset 0xAC which sounds a lot like the one in the Player entity, so I called it anim for now especially since it seems connected with animations.
This finishes this shield. I'm going to try to go through all the shields in the weapon overlays and get them done, they seem like some of the most complicated since a lot of the shield spells do some kind of crazy stuff with graphics.

Decompile w58 (Alucart Shield) EntityWeaponAttack

---

src/weapon/w_052.c

Shield work seems to be going well! Here's the next one.

Decompile Alucard Shield EntityWeaponShieldSpell

---

src/weapon/w_025.c

Nothing very special here, each shield seems to have different func_ptr_80170024 effects and this is one of them.

Decompile Goddess Shield func_ptr_80170024

---

src/weapon/w_025.c
src/weapon/w_028.c

Next shield, these seem to be coming together nicely, I'm looking forward to being able to study and compare all the shields when they're done.

Decompile Goddess Shield EntityWeaponShieldSpell

---

include/entity.h
include/sfx.h
src/weapon/w_024.c

Yet another one, seems many of these shields are padding out the struct as we go since we now have an unkA0.

Decompile Dark Shield func_ptr_80170024

---

include/entity.h
src/weapon/w_023.c

Continuing along. This one was a bit tough to work out with all the gte transformations, but thankfully we made it work.

Decompile Herald Shield func_ptr_80170024

---

src/weapon/w_015.c

Decompiles `func_ptr_80170008` of `w015`.

Decompile `func_ptr_80170008` of `w015`

---

include/sfx.h
src/weapon/w_023.c

Nothing super special, pretty similar structure to some other shield spells.

Decompile Herald Shield EntityWeaponShieldSpell

---

src/weapon/w_007.c

Decompile's `w_007`'s `func_ptr_80170008`.

Decompile `func_ptr_80170008` in `w_007`

---

include/game.h
src/weapon/w_011.c

Next one! Lots of collisions here which is interesting.

Decompile Axelord Shield func_ptr_80170024

---

src/weapon/w_011.c

Next one! Mostly copied and pasted from other shield spells.

Decompile Axelord Shield EntityWeaponShieldSpell

---

src/weapon/w_010.c

Coming real close to the end now! This finishes the Iron Shield, leaving only Knight and Leather shields.

Decompile Iron Shield EntityWeaponShieldSpell

---

src/weapon/w_009.c

It's been a while now between when I decompiled this one and when I'm now getting around to submitting the PR, but I think this one is pretty similar to other shield spells, there's a lot of shared code amongst them.

Decompile Knight Shield EntityWeaponShieldSpell

---

src/weapon/w_006.c
src/weapon/w_016.c
src/weapon/w_022.c

* `w_006` - `func_ptr_80170008`
* `w_016` - `func_ptr_80170010`
* `w_022` - `EntityWeaponAttack`

Decompile Various Weapon Functions

---

src/weapon/w_018.c

Decompile `func_ptr_80170004` of `w_018`

Decompile `func_ptr_80170004` of `w_018`

---

src/weapon/w_033.c

Decompile `EntityWeaponAttack` for `w_033`

Decompile `EntityWeaponAttack` for `w_033`

---

src/weapon/w_031.c

Decompiling `w_031` `EntityWeaponAttack`

Decompiling `w_031` `EntityWeaponAttack`

---

src/weapon/w_053.c

Decompile `EntityWeaponAttack` of `w_053`

Decompile `EntityWeaponAttack` of `w_053`

---

src/weapon/w_007.c
src/weapon/w_019.c
src/weapon/w_048.c
src/weapon/w_049.c
src/weapon/w_050.c
src/weapon/w_055.c

Includes:
* [EntityWeaponAttack_w_007](https://decomp.me/scratch/lCxkO)
* [EntityWeaponAttack_w_019](https://decomp.me/scratch/TjALo)
* [EntityWeaponAttack_w_048](https://decomp.me/scratch/9pB1k)
* [EntityWeaponAttack_w_049](https://decomp.me/scratch/TSgnD)
* [EntityWeaponAttack_w_050](https://decomp.me/scratch/gbcQV)
* [EntityWeaponAttack_w_055](https://decomp.me/scratch/D1WyG)

Decompile a number of similar EntityWeaponAttack funcs

---

CMakeLists.txt
config/splat.us.weapon.yaml
src/weapon/w_045.c
src/weapon/weapon_private.h

Unfortunately this build will fail until the fix is merged to decouple `func_ptr_*` signatures.
* [func_ptr_80170004_w_045](https://decomp.me/scratch/OmJXk)
* [func_ptr_8017000C_w_045](https://decomp.me/scratch/c5Qrm)

Finish w_045 and import data

---

src/st/np3/49F98.c
src/st/nz0/e_bloody_zombie.c

This was an ugly old function with lots of casts and `ext.generic`. I found an identical function in NP3 and copied it out.
I left a comment in the other file about this, for the sake of future potential de-duplication. For now, at least both functions are modern.

Update NZ0 EntityBloodSplatter

---

include/entity.h
src/servant/tt_000/45E4.c
src/st/sel/3585C.c
src/st/st0/2C564.c

My last few PRs have been targeting `ext.generic.unk8C` and removing them one by one. This finishes the job. Next I'll start digging into `unk88` :)

Eliminate remaining uses of ext.generic.unk8C

---

CMakeLists.txt
config/splat.us.weapon.yaml
src/weapon/w_007.c
src/weapon/weapon_private.h

https://decomp.me/scratch/Zn2uO

Finish w_007 and import data

---

include/entity.h
src/weapon/w_030.c

https://decomp.me/scratch/TPASg

Decompile func_ptr_80170010_w_030

---

include/entity.h
src/weapon/w_006.c

https://decomp.me/scratch/Gwx79

Decompile func_ptr_80170004_w_006

---

include/entity.h
src/st/sel/3410C.c
src/st/sel/3585C.c

Gradually removed each use of this variable, now the last one is gone so it's removed from the ext as well :)

Eliminate ext.generic.unk88

---

src/weapon/w_049.c

* [func_ptr_80170004_w_049](https://decomp.me/scratch/zDGOj)
* [func_ptr_8017000C_w_049](https://decomp.me/scratch/1iQj7)
* [func_ptr_80170010_w_049](https://decomp.me/scratch/DarwY)

Decompile remaining `w_049` funcs

---

tools/display_texture.py

A tool I made that allows you to identify some entities based on the primitives that they create. Usage is documented at top of the file. Allows extraction of images, which has already been useful in a few places.
Happy to provide any assistance with using this; it's come in handy for me and hopefully will be beneficial for others too.

Add texture viewer tool

---

include/game.h
src/dra/7E4BC.c
src/dra/843B0.c
src/dra/8A0A4.c
src/ric/2C4C4.c
src/st/sel/3642C.c
src/st/st0/3D8F0.c
src/weapon/w_006.c
src/weapon/w_007.c
src/weapon/w_012.c
src/weapon/w_019.c
src/weapon/w_043.c
src/weapon/w_046.c
src/weapon/w_048.c
src/weapon/w_049.c
src/weapon/w_054.c
src/weapon/w_056.c

Finishes the migration from `FLAG_UNK_800000` to `FLAG_HAS_PRIMS`.

Replace `FLAG_UNK_800000` with `FLAG_HAS_PRIMS`

---

src/weapon/w_015.c

* `EntityWeaponAttack`
* `func_ptr_80170010`
* `func_ptr_8017000C`

Decompile Remaining `w_015` Functions

---

tools/display_texture.py

Should have thought of this to begin with!
This makes the script fetch the VRAM while PCSX is running. That way you don't have to deal with keeping files around on your hard drive if you don't want to.

Add ability for texture viewwer to load from an active PCSX instance

---

include/entity.h
src/weapon/w_014.c

https://decomp.me/scratch/9Y8Zd

Decompile EntityWeaponAttack_w_014

---

include/entity.h
src/weapon/w_047.c

https://decomp.me/scratch/MD20i
Thanks @bismurphy for solving the last few swaps!

Decompile EntityWeaponAttack_w_047

---

src/weapon/w_050.c

Finished off work of several decomp.me anons.
`func_162000_8017B784`'s signature didn't seem to match, so I decomped the PSP version to check. This has been updated to a matching version which matches both PSP and PSX.

Decompile `func_ptr_80170004` of `w_050`

---

src/dra/7A4D0.c
src/ric/1AC60.c
src/ric/1CB04.c
src/ric/20920.c
src/ric/21250.c
src/ric/24788.c
src/ric/319C4.c
src/ric/pl_anims.c
src/ric/ric.h

Follows #1588 with some other minor discoveries

RIC more docs

---

src/st/mad/11D3C.c

Derived from a scratch by @hohle :)
Got it down to one FAKE line, which is sad but I'm okay with, especially with how weird and difficult MAD functions seem to be.

Decompile MAD func_80192408

---

config/symbols.us.bomar.txt
src/boss/mar/17FEC.c

EntityClockHands

---

config/symbols.us.bomar.txt
src/boss/mar/17FEC.c

EntityBirdcageDoor

---

config/symbols.us.bomar.txt
include/entity.h
src/boss/mar/17FEC.c

EntityStatue

---

config/symbols.us.bomar.txt
include/entity.h
src/boss/mar/17FEC.c

EntityStoneDoor

---

include/entity.h
src/st/no3/4AFF0.c
src/st/no3/no3.h

https://decomp.me/scratch/XWQUk
I'm sure there's some non-idiomatic code I've written here so looking forward to rewriting some 😄

Decompile `no3` `EntityExplosion3`

---

src/boss/mar/17FEC.c

Think this was missed in #1665 yesterday

Fix a couple of other `SFX_STONE_MOVE_*` in `boss/MAR`

---

config/symbols.pspeu.tt_000.txt
config/symbols.us.tt_001.txt
src/servant/set_entity_animation.h
src/servant/tt_000/10E8.c
src/servant/tt_001/F84.c

Last full dupe across these too. Thanks sozud for clearing up the file splits for me in #1683

Deduplicate `SetEntityAnimation` function in `tt_000` and `tt_001`

---

.github/workflows/validate-and-report.yml
tools/function_finder/function_finder_psx.py

Had an idea, not sure if this is useful or not but I figured it might help give an indication for newer people or those not in the Discord loop if code is already duplicated when looking at the function report.
Here's an example output from the current state (minus the scratches which didn't seem to load for me locally so I skipped them)
[functions.md](https://github.com/user-attachments/files/17162454/functions.md)
@bismurphy guessing this would be your area of expertise 😄

Add duplicate match info to function report

---

.github/workflows/validate-and-report.yml
tools/function_finder/function_finder_psx.py

Reverts Xeeynamo/sotn-decomp#1685

Revert "Add duplicate match info to function report"

---

config/splat.hd.dra.yaml
config/splat.hd.ric.yaml
config/splat.hd.stwrp.yaml
config/splat.hd.tt_000.yaml
config/splat.pspeu.stwrp.yaml
config/splat.pspeu.tt_000.yaml
config/splat.us.bomar.yaml
config/splat.us.borbo3.yaml
config/splat.us.dra.yaml
config/splat.us.main.yaml
config/splat.us.ric.yaml
config/splat.us.stcen.yaml
config/splat.us.stdre.yaml
config/splat.us.stmad.yaml
config/splat.us.stno3.yaml
config/splat.us.stnp3.yaml
config/splat.us.stnz0.yaml
config/splat.us.strwrp.yaml
config/splat.us.stsel.yaml
config/splat.us.stst0.yaml
config/splat.us.stwrp.yaml
config/splat.us.tt_000.yaml
config/splat.us.tt_001.yaml
tools/dups/src/main.rs
tools/make-config.py

This is prep for fixing our tooling and all the force_extract stuff. Weapon0 doesn't seem to match with this setting on for some reason?

Turn on disassemble_all for most yamls

---

src/gamemeta.js

Reverts Xeeynamo/sotn-decomp#1797

Revert "Add RBO3"

---

config/splat.us.borbo3.yaml
config/symbols.us.borbo3.txt
include/entity.h
include/sfx.h
src/boss/rbo3/rbo3.c
src/boss/rbo3/rbo3.h

Decompiles `func_us_80191438`, `func_us_8019179C`, and `func_us_80192B38`.
Imports `func_us_80192020` and `func_us_80192998` from #557.

Decompile RBO3 Functions

---

src/st/e_skeleton.h
src/st/no0/e_slinger.c

Thanks to sozud for the suggestion

Refactor some common skeleton bone throw code for clarity

---

include/entity.h
src/st/st0/39EA8.c

This uses a few separated elements of its Ext; I suspect this corresponds to this Ext being shared across the entities in this file, but that kind of consolidation can be something we do in the future when they're all done.
Anyway, another GTE-heavy function completed!

Decompile ST0 EntityClockTower3D

---

config/splat.us.stst0.yaml
include/entity.h
src/st/st0/3D8F0.c
src/st/st0/bss.c
src/st/st0/create_entity.c

Another one down!
In terms of the sequence of functions, this is the last function in the ROM for ST0. The split between C and BSS was off by one (the NOP after the RA for this function was being pulled in as part of the 00 bytes in BSS), so I had to make some small BSS fixes to get a match. All good now!
I believe this leaves only a single ST0 function remaining.

Decompile ST0 EntityBackgroundVortex

---

include/entity.h
src/servant/tt_002/3678.c

The 2nd argument to func_us_80173994 is probably either some flags or needs to be an enum.  But I am not sure what they are yet.  I'll come back to clean them up once I get that function decompiled.

Decompiling function func_us_80173BD0

---

include/entity.h
include/game.h
src/servant/tt_002/3678.c

Full match both PSP and PSX
PSX: https://decomp.me/scratch/iF9Ax
PSP: https://decomp.me/scratch/bA5Ta
I made a comment in the code that it looks like the extension used by this entity is wrong, but I don't have enough context to build a "correct" one yet.  We'll have a better idea as we get more functions decompiled (especially the functions that spawn these sub entities).

decompiling func_us_80177AC4

---

src/st/no0/57C20.c

This is my first PR to this project, started with a small function

decompile func_us_801D7C20

---

config/splat.us.borbo3.yaml
config/symbols.us.borbo3.txt

Some small fixes to RBO3 symbol map and BSS layout.

RBO3 Config Fixes

---

include/entity.h
src/servant/tt_002/3678.c

The data structure for the ranked lookup table is messy because the PSP version requires it to be a flat array.
I'm pretty sure I have a union solution for that so the data tables will at least make sense, but until I can get data import done, we'll keep it like this as it will need to be used like this anyway.
PSX: https://decomp.me/scratch/SN6vr
PSP: https://decomp.me/scratch/DM13D
PSP has a register swap that I couldn't figure out, but is largely a match

Decompile tt_002 func_us_80176504

---

src/st/no0/e_ctulhu.c
src/st/no0/e_init.c
src/st/no0/no0.h

`func_us_801DA488` / `EntityCtulhuFireball`
PSX: https://decomp.me/scratch/aCOVv
PSP: https://decomp.me/scratch/QYpzQ

Decompile `no0` Ctulhu fireball attack entity

---

src/st/no0/e_plate_lord.c

PSX : https://decomp.me/scratch/3Jaj8

Decompile `no0` func_us_801D4AA4

---

include/entity.h
src/st/no0/e_plate_lord.c

PSX: https://decomp.me/scratch/b6Rmt
PSP: https://decomp.me/scratch/5tcVT (Only register mismatch)

Decompile `no0` func_us_801D5074

---

src/st/no0/e_plate_lord.c

`func_us_801D4E94`
PSX: https://decomp.me/scratch/SVou4
PSP: https://decomp.me/scratch/5LMeJ
`func_us_801D4FCC`
PSX: https://decomp.me/scratch/GelZ1
PSP: https://decomp.me/scratch/7LG1P

Decompile `no0` func_us_801D4E94 and func_us_801D4FCC

---

src/weapon/w_030.c
src/weapon/weapon_private.h

Decompiles `func_ptr_80170004` of `w_030`

---

src/st/no1/unk_4F57C.c

PSX: https://decomp.me/scratch/3Iexa
PSP: https://decomp.me/scratch/WT5AS

Decompile `no1` func_us_801D04B8

---

include/entity.h
src/st/no1/e_skeleton_ape.c
src/st/no1/no1.h
src/st/no1/unk_3FA34.c
src/st/no1/unk_5348C.c

Miscellaneous outer wall functions and function documentation.

Skeleton Ape Barrel, Elevator Activated Support Function

---

src/st/no1/e_armor_lord.c
src/st/no1/no1.h

`func_us_801D1184`:
PSX: https://decomp.me/scratch/du3bO
PSP: https://decomp.me/scratch/nzXYf
`func_us_801D1388`:
PSX: https://decomp.me/scratch/3oS5u
PSP: https://decomp.me/scratch/Qzl5b

Decompile `no1` func_us_801D1184 and func_us_801D1388

---

include/entity.h
src/st/no1/no1.h
src/st/no1/unk_54400.c

PSX: https://decomp.me/scratch/EwUgM
PSP: https://decomp.me/scratch/ltzeA

Decompile `no1` func_us_801D4400

---

config/splat.hd.ric.yaml
config/splat.hd.stcen.yaml
config/splat.pspeu.stst0.yaml
config/splat.us.bomar.yaml
config/splat.us.borbo3.yaml
config/splat.us.stlib.yaml
config/splat.us.stno0.yaml
config/splat.us.stno1.yaml
config/splat.us.tt_001.yaml
config/splat.us.tt_002.yaml
config/splat.us.tt_003.yaml
config/splat.us.tt_004.yaml
tools/make-config.py
tools/requirements-python.txt

Reverts Xeeynamo/sotn-decomp#2164

Revert "Upgrade splat to 26.0"

---

config/symbols.us.txt
include/entity.h
include/sfx.h
src/st/lib/e_shop.c
src/st/lib/first_c_file.c
src/st/lib/lib.h

`func_us_801B15C0`:
PSX: https://decomp.me/scratch/G2jsB
PSP: https://decomp.me/scratch/vEgRa
`func_us_801B11A0`:
PSX: https://decomp.me/scratch/14Bbe
PSP: https://decomp.me/scratch/uVDtw
`func_us_801B0FBC`:
PSX: https://decomp.me/scratch/q7c6a
PSP: https://decomp.me/scratch/JP0c0

Decompile `lib` func_us_801B15C0 + helpers

---

include/entity.h
src/st/lib/unk_36F30.c

PSX: https://decomp.me/scratch/jiK9K
PSP: https://decomp.me/scratch/bUWNR

Decompile `lib` func_us_801B8A00

---

Makefile.psp.mk
config/splat.pspeu.stwrp.yaml
config/symbols.pspeu.stlib.txt
src/st/entity_stage_name_popup_jp.h
src/st/lib/lib.h
src/st/lib_psp/e_stage_name.c
src/st/wrp_psp/e_stage_name.c

Resubmitting after progress.py fix

Decompile e_stage_name for PSP `wrp` / `lib`

---

config/symbols.pspeu.stlib.txt
include/primitive.h
include/unkstruct.h
src/st/lib/e_lesser_demon.c
src/st/lib_psp/unk_1D9E8.c
src/st/nz0/e_spittle_bone.c

PSX: https://www.decomp.me/scratch/cB8gC
PSP: https://www.decomp.me/scratch/Av6Re
Also took the opportunity to:
- Remove Unkstruct_801C6C6C, which was only used by EntitySpittleBoneSpit.
- Convert EntitySpittleBoneSpit to use the Pos struct.
- Copy PSP conditional block to EntitySpittleBoneSpit expecting it to be needed for future code sharing.

Decompiled `lib` func_us_801BBAB4/func_psp_09256018

---

.github/workflows/dockerfile.yaml
Dockerfile

Fix master after merging #2434 . Putting this PR here in case it doesn't work at first try

Fix Dockerfile build on CI

---

src/boss/rbo5/doors.c

Thanks to everyone for the help

Decompile rbo5 func_us_801B5004

---

config/symbols.us.bobo4.txt
src/boss/bo4/unk_46E7C.c
src/boss/rbo5/unk_4648C.c

Another Alucard-like function.

`EntityMist` for `BO4` and `RBO5`

---

src/st/no2/unk_33A94.c

Decompiled func_us_801B41A4. It came out of decomp.me perfect the first time (https://decomp.me/scratch/PGlSR).
Let me know if there are any issues. It recompiled correctly for me on my end.

Decompiled func_us_801B41A4

---

src/st/no2/33D8C.c
src/st/no2_psp/1FF58.c

PSX version: https://decomp.me/scratch/OJWQD
PSP version: https://decomp.me/scratch/dyfOu

Decompiled func_us_801B3D8C / func_pspeu_092575D8

---

src/gamemeta.js

Adds progress for missing overlays.

Add Overlay Progress

---

config/symbols.us.sttop.txt
src/st/top/296F4.c
src/st/top/cutscene.c
src/st/top/e_clock_tower.c
src/st/top/e_init.c
tools/make-config.py

EntityTriangleElevator, TOP_EntityCutscene, EntityClouds

Remaining TOP Functions

---

src/main/psxsdk/libgpu/sys.c

`_exeque`: https://decomp.me/scratch/ij8G6
`_addque2`: https://decomp.me/scratch/iSyoQ

Decompile `main` _exeque & _addque2

---

include/psxsdk/libcd.h
src/dra/cd.c
src/dra/sound.c
src/dra_psp/63C08.c
src/main/main.c
src/main/psxsdk/libcd/bios.c
src/main/psxsdk/libcd/iso9660.c
src/main/psxsdk/libcd/sys.c
src/st/sel/stream.c

Quick fix
I tried propagating the `Result_t` type but it became a huge change and I'm starting to think maybe we should just revert it to `unsigned char*`

Fix psp compilation error

---

tools/dups/src/main.rs
tools/progress.py

Add RTOP to dups and progress

---

config/symbols.us.main.txt
src/main/psxsdk/libspu/libspu_internal.h
src/main/psxsdk/libspu/s_gva.c
src/main/psxsdk/libspu/s_ini.c
src/main/psxsdk/libspu/s_sk.c
src/main/psxsdk/libspu/spu.c
src/main/psxsdk/libspu/sr_gaks.c

Mostly copied from @Mc-muffin s scratch:  https://decomp.me/scratch/Mcjwq

Decompile `SpuGetVoiceAttr`

---

src/st/cat/unk_3732C.c
src/st/cat/unk_44C7C.c

Hello, I was interested in the project and while messing around I got this little function to match. I don't know if I should do something else. Maybe I can maybe tackle the other functions in `cat`, so that the PR gets a little more substantial...

Decomp of func_us_801C5600 and func_us_801B8474

---

src/main/psxsdk/libsnd/vmanager.c

https://decomp.me/scratch/1KjjN

Decompile `SpuVmKeyOnNow`
