- .github/workflows/validate.yml
- Makefile
- tools/requirements-python.txt
Creates a workaround to force using spimdisasm 1.9.0 as 1.9.1 currently breaks the repo
> Fix GitHub pipeline

- src/dra/42398.c
Based on examining func_801093C4, which calls this function, I think the argument is an entry of D_80086FEC (POLY_GT4). However this struct layout doesn't seem to fit. I saw that other functions have the same issue so I left it for now.
> Decompile func_800EDB08

- src/dra/42398.c
The accelerationX reference seems to be required to match.
> Decompile func_801167D0

- tools/find_duplicates.py
I realized there was a print bug if there was no duplicates found.
> [Tool] small str concatenate fix

- include/game.h
Often when I decompile an entity I get `extern ? (*g_api_AllocPrimitives)(s32, s32, s32);` which is obviously wrong. By adding some helper signatures in `game.h` the mips2c output should look a bit nicer and remove a bit of busy-work out from our shoulders.
> GameAPI helper signatures

- tools/function_finder_saturn.py
This does basically the same thing as the PSX one except I went with markdown for nicer formatting. The script has to do enough things differently I thought it would be cleaner to keep them separate. An example output is at https://github.com/sozud/sotn-decomp/blob/saturn_function_finder/funcs_sat.md
I ignore functions from 0.BIN in the SEGA libraries section. This doesn't integrate with the CI yet since it's hard to test on my branch.
> Add saturn function finder script

- .github/workflows/validate-and-report.yml
- Makefile
- src/dra/42398.c
- src/dra/47BB8.c
- src/dra/5298C.c
- src/dra/5D6C4.c
- src/dra/62D70.c
- src/dra/692E8.c
- src/dra/71830.c
- src/dra/73AAC.c
- src/dra/75F54.c
- src/dra/953A0.c
- src/dra/cd.c
I can only hope it will work at first try.
The trick lies in `extract: extract_$(VERSION)` and `build: build_$(VERSION)` to customise different versions/ports to do different things and keep the flow the same.
You can now do:
```
export VERSION=hd
make build
```
or:
```
VERSION=hd make build
```
or:
```
make build_hd
```
If we are happy with this pattern we might want to do the same with the Saturn version too.
> Integrate HD build to the CI

- src/dra/692E8.c
This is a really weird function. It has several calls to PlaySfx which use 3 arguments, for example `PlaySfx(0x64C, 0x30, 0);`.
There is one last Goto which I was not able to remove. Notice that this function has many, many return statements. My handling of these might be related to the remaining Goto. I generally, when possible, used structures like:
```
if(cond1){
doThingA;
return 1;
}
doThingB;
```
which could equally well be written as
```
if(cond1){
doThingA;
return 1;
} else {
doThingB;
}
```
And it is possible that some rearranging of those if-else blocks would remove the Goto. It's a bit odd that the compiled code does a jump where it does.
I believe this function is responsible for much of Alucard's vertical acceleration management, especially what comes from player input. We do …
> Decompile DRA func_8010FDF8

- .gitignore
- tools/analyze_calls.py
Very happy to have this working!
Now, when you run `python3 analyze_calls.py ALL`, it will generate the call graphs for every function in the game, and save as an SVG file in the directory `tools/generated_graphs`. It will then finish by creating an `index.html` that links to every one of those graphs. Each graph's bubbles are clickable to take you to the next graph.
I have deployed an example of the result of this, linked in the sotn decomp Discord, but because it is hosted on my personal computer, I will not be linking it here (accessible to the wider internet and crawlers, etc). It would be great if this script could be worked into the CI to create a publicly visible list of functions linking to graphs, which would automatically update whenever the repo gets updated.
As always, be sure …
> Generate web pages for call trees

- include/game.h
- src/dra/5298C.c
- src/dra/5D6C4.c
I checked this by editing the level of the familiar and looking at the familiar status menu. The JP only ones still get shown in the menu if you have the relic.
> Document familar IDs

- src/main/psxsdk/libsnd/libsnd_internal.h
- src/main/psxsdk/libsnd/miditime.c
I'm not sure about `struct SeqStruct* temp_a1 = &_ss_score[arg0][arg1];` since it doesn't seem to make sense with the struct definition. I got the idea from https://github.com/AliveTeam/sound_rev/blob/7a9223139c3375bf10e96a4ac17d77b973979e20/psx_seq_player/lib_snd.cpp#L201
Co-authored-by: Mc-muffin <8714476+Mc-muffin@users.noreply.github.com>
> Decompile _SsReadDeltaValue

- Makefile
- config/splat.us.weapon.yaml
- diff_settings.py
- include/entity.h
- include/game.h
- include/macros.h
- include/weapon.h
- src/dra/692E8.c
- src/dra/71830.c
- src/dra/73AAC.c
- src/dra/75F54.c
- src/dra/dra.h
- src/saturn/sattypes.h
- src/weapon/header.c
- src/weapon/w_000.c
- tools/decompile.py
Matches w_000, effectively opening the doors to understand how hand equippables work. That includes weapons, shields, consumable; all of them internally named as Weapons). This overlay is used by:
* Tyrfing
* Namakura
* Gladius
* Scimitar
* Cutlass
* Saber
* Falchion
* Broadsword
* Bekatowa
* Damascus sword
* Hunter sword
* Bastard sword
* Talwar
* Sword of Hador
* Luminus
* Harper
* Gram
* Mormegil
* Terminus Est
* Dark Blade
* Mourneblade
* Badelaire
Due to the nature of splat, renaming the symbols is hella hard but possible once we start importing the `.data` section in it. As far I know this overlay does not contain any `.rodata`.
Checklist to convert it from Draft to Ready:
> w_000 matching

- tools/dups/Cargo.toml
- tools/dups/src/levenshtein_hashmap.rs
- tools/dups/src/main.rs
- tools/dups/src/types.rs
This adds an equivalent of find_duplicates.py to tools/dups. This runs in about 2 minutes on my machine so it should be significantly faster on the CI. The algorithm isn't exactly the same so the report is a little different. Here's an example:
https://gist.github.com/sozud/503fd3b3014668e6644fb2dfae51d5e5
This works by grouping all the functions in to clusters, basically:
```
if levenshtein_similarity > threshold
cluster.append(current_function)
```
Memoization gives a little speedup to avoid computing the levenshtein distance for the same pairs over and over again. This is still a brute-force algorithm. I did some research and there's a lot of similar problems but didn't find something that seemed like it would be a good fit. I think this is probably fast enough to last for a while.
> Add duplicates report to dups tool

- tools/analyze_calls.py
Small bugfix, little overall impact. Should be able to merge, but if you're curious what I changed here:
One of the important functions in analyze_calls is the one that resolves ambiguous function names for duplicates. For example, when UpdateEntityRichter calls UpdateAnim, it is unclear whether it is calling the `dra` version of that function, or the `servant` version of that function. `find_func_match` aims to resolve those ambiguities by matching based on the file paths. Something which is in, for example, `no3`, is almost certainly calling the `no3` version of a function. We can resolve the vast majority of function naming ambiguities this way.
Due to an oversight in an `assert` statement (forgot to use an ==1), we were not properly detecting failures in resolving those ambiguities. …
> Fix small bug in analyze_calls

- src/dra/5D6C4.c
Very slight changes here.
I was reading through DealDamage and found a couple changes that make the function more straightforward. We use the stats enum (rather than the numbers 0-3), and we use the name "highest" rather than "higher" to find the highest value in an array.
> Improve documentation on DealDamage

- tools/analyze_calls.py
As requested by Sozud, this will sort the callees and callers alphabetically when generating the call graphs. Therefore, between two runs of the tool, the result should be more deterministic.
This also has the nice side effect that, because sorting places capital letters first, decompiled functions with names with capital letters (such as **A**llocEntity) will be placed before those with func_, so they are highlighted.
Of course, if a function's name changes, it will move around in the call graphs, but hopefully this change will mean we only see movement in the graphs between two CI runs in the places where relevant changes have occurred.
> Sort callers and callees in analyze_calls.py

- tools/analyze_calls.py
In the interest of improving the diffs shown in "Update reports" commits (example here: https://github.com/Xeeynamo/sotn-decomp/commit/50e507f0c0e0cccfbdaaa83be521f1af3884ee1d), we recently changed the SVG generation code to be more deterministic, such that any differences are only the result of actual changes to the source code of the repo.
While perusing this latest diff, I noticed that the index.html is showing as a "large diff", which is because the generated HTML code does not contain any newlines. To be clear, HTML has its own tags which control the lines in the final rendered page, but the actual text in the HTML file does not care about whether the code is on multiple lines or is all in one line. 
For the sake of generating diffs, it is heavily preferred for the HTML to run as …
> Make the analyze_calls index.html properly use multiple lines

- src/weapon/w_000.c
- src/weapon/w_004.c
Given the fact `func_ptr_80170020` is called as an effect of the Shield Rod, I decided to decompile it. Unfortunately I couldn't find any extra code to handle that logic. It is almost identical to `w_000`
> Decompile Shield Rod

- include/entity.h
- src/weapon/w_015.c
- src/weapon/w_040.c
- src/weapon/w_041.c
- src/weapon/w_042.c
As w_042 is similar to w_040 I decided to decompile them both.
`EntityWeaponAttack` is the vial dropping to the ground. When `CheckCollision` detects a collision with the solid pavement, the vial gets immediately destroyed. There is some wild magic happening, which I think it's happening when the code does `g_api.func_8011AAFC(`. That might trigger the function `func_ptr_80170004`, which will summon the vial monster.
The state machine of the summon itself. We have `self->unk1A` and `self->unk1C`, which if I recall correctly they indicates ScaleX and ScaleY respectively. `self->unk19 |= 3` will tell to use both horizontal and vertical scaling. When the scaling reaches 100% (or `0x100`) after 64 frames, the summon will get inherit the properties of... …
> Decompile all w_040 and w_042

- tools/function_finder/function_finder_psx.py
When `analyze_calls` creates an SVG file, the name of that file consists of the overlay name, then a dot, then the function name. This is intended to ensure that we get a unique name for the file, given that the function name alone will often lead to a duplicate. The function finder was using an incorrect filename-finding logic.
This works on my machine, hopefully it will work in CI too. Unfortunately this is the type of PR which we won't know if it works until fully merging. The logic is fairly straightforward though, so hopefully this performs as intended.
> Fix function finder svg filenames

- src/dra/8D3E8.c
I'm decompiling func_8012EF2C and everything that it calls, because this seems to be an important section which calls the functions I've been exploring lately. This is one of the functions called by that one.
Nothing super special here.
> Decompile DRA func_8012DF04

- .github/workflows/validate-and-report.yml
As suggested by @delta-473, GitHub recently shipped their [caching mechanic for the CI](https://github.com/actions/cache/blob/main/caching-strategies.md). I can think of a few ways it can get used in our advantage:
* Cloning the "dependencies": it should save cloning about 4GB of data to every commit on `master` and about 1.5GB per PR.
* Using this cache instead of artifacts to export the `.map` files to calculate the decomp progress
* Same as above but to the reporting step.
This PR just addresses the first point as it is the heaviest burden of the CI so far and it is what I think a quick win.
> Ci pipeline speedup with cache

- src/dra/75F54.c
Function called by func_8012EF2C in case 1. Relatively small and simple.
The hard-coded g_Entities[17] is a little odd, might be interesting to see what entity uses that slot when this function is called.
> Decompile DRA func_8012D024

- tools/analyze_calls.py
When we generate all the function graphs in analyze_calls, we generate an HTML file which contains links to all of them. Example here: https://github.com/Xeeynamo/sotn-decomp/blob/gh-duplicates/function_calls/index.html Unbeknownst to me, Github does not allow you to view it as a rendered HTML page. You can only view it as raw text. There are workarounds like https://htmlpreview.github.io/?https://github.com/Xeeynamo/sotn-decomp/blob/gh-duplicates/function_calls/index.html but that's a bit clumsy and you can't get to it directly from the repo.
On the other hand, we have Markdown pages like https://github.com/Xeeynamo/sotn-decomp/blob/gh-duplicates/functions.md which render nicely and are usable from Github directly.
This attempts to generate a Markdown page which should be effectively …
> Generate markdown directory to function graphs

- tools/analyze_calls.py
Small change here, just linking to the raw SVG so it's clickable. The github preview makes the bubbles no longer operate as links.
While we're at it, would it be okay if I moved the function_graphs.md up a directory, so that it sits alongside duplicates.md and functions.txt, rather than being mixed in the function_calls folder with all the svgs?
> Make markdown page link to raw version of svg

- include/unkstruct.h
- src/dra/5D6C4.c
- src/dra/dra.h
A while ago, I decompiled func_800FE97C, creating Unkstruct_800FE97C for its primary parameter.
It turns out that EntityAlucard calls both AlucardHandleDamage and Unkstruct_800FE97C with the same argument, and furthermore, AlucardHandleDamage has already had a struct made for it called DamageParam.
Therefore, I am deprecating the UnkStruct, merging the known struct members, and changing everything to use DamageParam going forward.
I think we're still a long way from decompiling EntityAlucard, but I am going to start trying to learn some hints from it going forward. This is the first of those.
> Change func_800FE97C to use preexisting DamageParam struct

- tools/analyze_calls.py
Markdown file is currently not being created in the CI. This rearranges how we manage that, and also adds a debugging line which might help. I don't know the nature of the error, but this will attempt to solve it, and if not, hopefully provide some kind of information to suggest why it isn't working.
> Attempt fixing analyze_calls markdown location

- include/game.h
- src/st/dre/173C4.c
- src/st/mad/EDB8.c
- src/st/no3/41C80.c
- src/st/np3/394F0.c
- src/st/nz0/39908.c
- src/st/nz0/47958.c
- src/st/st0/31CA0.c
- src/st/wrp/861C.c
Given that InitializeEntity copies these values from EnemyDef directly into Entity, and we have names for these struct members of Entity, it is reasonable to name the EnemyDef members to match.
Almost all the changes are in InitializeEntity since these struct members are rarely touched. A fairly straightforward find-and-replace.
> Finish EnemyDef struct members

- tools/analyze_calls.py
The classic "it works on my machine" :)
The method we use to gather the functions in `main` (which we do not currently fully process, but need to know about due to them being called in the game's functions) relied on the symbols file being complete. Now that orphan symbols are being removed and things are being moved around, this new method will search for them in a different way.
We look in asm/us/main and collect all files which are in that directory directly (That is, not in a subdirectory). As of now, that is:
asm/us/main/psxsdk_stuff.s
asm/us/main/C464.s
asm/us/main/header.s
asm/us/main/15F4.s
Then, we look for any `glabel` within there. So far, this appears to contain every function called within the game and successfully generate graphs. I can't guarantee that this will work, but I …
> Change analyze_calls to work with removed symbols in `main`

- src/st/sel/2C048.c
- src/st/sel/2D260.c
- src/st/sel/sel.h
Last function of today. I spent much more than I wanted to get a match. The evil `level = (&g_SaveSummary[port])->level[slot];` was the trick to get a match all along. On the surface it makes no sense. But it must be connected to a pattern we have yet to discover. Maybe the developers were accessing the arrays as `*(array + index)` instead of `array[index]` (I've seen that being the case in other functions), maybe they used some strange macros or maybe they used `inline` functions. If you want to have a play, this is the scratch: https://decomp.me/scratch/ZePxq
I took the opportunity to give some good names to the dependent function's arguments.
I am well aware I could have renamed `D_801BC3EC` and `D_801BAF08`. But as I am in the middle of decompiling …
> SEL func_801AE6D0

- src/dra/75F54.c
- src/dra/8D3E8.c
`HandleTransformationMP` is called in EntityAlucard, and by 3 other functions. One of those 3 was MistFormFinished, and the other two did similar logic for the bat and wolf forms. Therefore, this PR renames the other two to the same for bat and wolf.
Happy to change all 3 of these if we don't like the name, but whatever we do, all 3 should have the same naming structure, and this accomplishes that.
> Rename transformation exiting functions

- include/game.h
- src/dra/692E8.c
- src/dra/72BB0.c
- src/dra/75F54.c
- src/dra/8D3E8.c
A recently decompiled function found that `s32 D_80072BD0[8][9]` was actually an array of Collider. This PR updates that to be correct.
It looks like the struct member right after it should be grouped in to have `colliders[22]` but for whatever reason that doesn't seem to work so I'm leaving it. Given that the struct size matches and everything, we probably have `colliders[8]` and then `colliders2[14]` but without more evidence I don't want to mark this down yet.
Some of these lines come out pretty long like if `((g_Player.colliders[1].effects & (EFFECT_SOLID_FROM_BELOW + EFFECT_SOLID)) == EFFECT_SOLID ||`. Here is what that looks like after I run the formatter:
Personally, I think the original code is a lot more readable since everything is stacked up. You can see the [1][2][3] much more …
> PlayerState collider restructure

- config/splat.us.weapon.yaml
- include/entity.h
- src/weapon/w_029.c
Now that we fixed the `li` instruction, the other functions in this weapon file can come spilling out :)
There was a jump table that I changed to being rodata. Luckily that went smoothly.
Interestingly, this does the same %5 as the other function, but there are two spots where it uses g_Timer (the one that always runs) and one other where it uses g_GameTimer (the one that pauses when the game pauses). It's only palettes so it doesn't really matter, but it's neat.
One problem: This stores two bytes to self->7C and self->7D. But we already had a different weapon that used 7C as a s16. So we may end up needing to make different `ext` entries for the different weapons. For now, I'm leaving it generic.
> Decompile w_029 EntityWeaponShieldSpell

- config/splat.us.weapon.yaml
- src/weapon/w_029.c
Continuing to finish out w_029 now that we have g_GameTimer % 5 figured out.
There is a very unfortunate thing here. We are using `self->ext.weapon.lifetime`, but EntityWeaponShieldSpell just had a whole mess about 7C and 7D and needing to create ext.weapon29. Clearly, weapon29 references this location as both a s16, and as two u8's. I really don't know what to make of that. Happy to adjust things here if we want to handle that differently, but for now this seems to work. It will be cool if we can get this strange weapon fully decompiled.
> Decompile w_029 EntityWeaponAttack

- include/entity.h
- src/weapon/w_029.c
This one was big and complicated. It rounds out w_029; there is no longer any INCLUDE_ASM in this, so that's cool.
I believe this function controls the shield rod spell with the fire shield, but I can't guarantee that. This required creating a new struct, which I called FireShieldDragon. I put it in the .c file since I don't expect anything else to use that struct so it doesn't need to be in a .h file.
Overall this function could probably use some study and cleanup, but for now it works and it's great to have the whole function decompiled. Nobody will ever have to deal with the `-O1` of this function ever again :)
> Decompile w_029 func_ptr_80170024

- config/splat.hd.dra.yaml
- config/splat.us.dra.yaml
- config/symbols.hd.dra.txt
- config/symbols.us.dra.txt
- src/dra/704D8.c
- src/dra/71830.c
- src/dra/dra.h
Mostly more of the same.
A bit interesting, most of the timers get set to 24, where the other spells all used 20. Seems the developers wanted to make Soul Steal slightly easier, likely due to the complicated input.
Interestingly, for the first button, in case 0, there is a discrepancy based on whether you start the spell facing left or right. If you start facing left (so your first press is back, to the right), you get 20 frames, while facing right gives 24. Not sure if this is worthy of a `@bug` annotation?
> Decompile DRA CheckSoulStealInput

- src/dra/5087C.c
- src/dra/dra.h
This one is already decompiled, but I noticed that there are some minor issues.
One is that it has a return type of bool, but it is able to return the result of func_800F087C, which is itself an s32. Therefore, this should return s32.
While we're at it, there was a nested if-statement that doesn't need to be nested, so I un-nested it.
Nothing huge, but I think this makes the function slightly better. Main thing is getting the return type right.
> Improve DRA SetNextRoomToLoad

- src/dra/5298C.c
- src/dra/dra.h
Helping with the effort to finish out 5298C.c.
This is connected to the chain for analysis of Japanese text. It calls func_80106A28, which is my next big target I'm working on.
Lots of placeholders and stuff here, but at least it matches.
Thank you @sozud for the help with the final matching step :)
> Decompile DRA func_800F98AC

- include/unkstruct.h
- src/st/entity_enemy_blood.h
After decompiling the Vibhuti in my last PR, I looked at the pattern I had noticed, where users of FakePrim would call `func_800EDB58`. I then looked to that function's callers: https://raw.githubusercontent.com/Xeeynamo/sotn-decomp/gh-duplicates/function_calls/dra.func_800EDB58.svg
Clearly, EntityEnemyBlood uses this function. Sure enough, when I examined that function in its current state, I found that it has a bunch of ugly casts which directly match FakePrim. Therefore, this PR changes it to use FakePrim so that it does not need all those casts anymore. Additionally, we find in this function that the velocity is being changed by another member in the struct, which tells us that this member is acceleration. Therefore, FakePrim is being understood more and more.
> Use FakePrim on EntityEnemyBlood

- config/splat.us.stno3.yaml
- src/st/cen/1B274.c
- src/st/cen/cen.h
- src/st/dre/1E1C8.c
- src/st/dre/dre.h
- src/st/mad/15520.c
- src/st/no3/564B0.c
- src/st/no3/no3.h
- src/st/np3/4E69C.c
- src/st/np3/np3.h
- src/st/nz0/49930.c
- src/st/nz0/nz0.h
- src/st/rwrp/14590.c
- src/st/rwrp/rwrp.h
- src/st/st0/36358.c
- src/st/st0/st0.h
- src/st/wrp/F420.c
- src/st/wrp/wrp.h
Not sure what this one does, but it's in all the overlays.
I couldn't get `mad` to work, since it gives errors when I reference functions like `RotMatrixZ` (which isn't even one of the new `gte_` defines). I figured we can leave that for later since `mad` is its own weird thing.
I also found an issue with the splat for `no3` where some boundaries were being drawn in the wrong places; this is now corrected which allows the function to work in that location.
The function takes a primitive as its argument and does some stuff with it. I don't know what it actually does. It appears that the different overlays use it in different places (and some overlays don't call it at all). The function loads an external SVECTOR from a variable, which I added to the `.h` file for each overlay. The vector is …
> Decompile highly duplicated GTE-using function

- src/dra/5298C.c
Came across this function.
Its main job is that it passes its arguments onward to `func_800F99B8` (these two functions are easy to confuse the names of, these numbers are too similar...)
Since the first argument of func_800F99B8 is a `const char*`, this function should be changed to match.
> Fix pointer argument for func_800F9D88

- src/dra/5D6C4.c
- src/dra/6D59C.c
- src/dra/704D0.c
- Rename func_800FF064 to HandleGravityBootsMP (call graph proves that this is the only use: https://raw.githubusercontent.com/Xeeynamo/sotn-decomp/gh-duplicates/function_calls/dra.func_800FF064.svg)
- Rewrite that function to use the CallMode system we developed earlier, and also rewrite it to not need the extra variable. Function is now much shorter.
- Rename func_8010E9A4 to DoGravityJump. This function sets Alucard's velocity to move up rapidly, spawns the gravity boot laser beam entity, and sets the player state machine's step.
- Fill in enums for SetPlayerStep in a few related places.
Overall I think this makes the logic more readable. Next going to look into g_Player.unk44 because that seems to be the last missing piece here.
> Refactor some functions with gravity jump

- config/symbols.us.ric.txt
- src/ric/1AC60.c
- src/ric/1FCD0.c
- src/ric/20920.c
- src/ric/21250.c
- src/ric/ric.h
- Main focus is an update of func_8015D020. That had a TODO to remove a variable, which I have now removed. I also used enums for player steps, and changed the speeds to use FIX(). I also cleaned up the control flow to remove the goto.
- While working on that function, I noticed that it calls an unnamed function. The duplicates list at https://raw.githubusercontent.com/Xeeynamo/sotn-decomp/gh-duplicates/duplicates.txt indicates that SetSpeedX was missing from RIC. I added that in now and adjusted all uses in RIC, including the ones in func_8015D020.
That's about it; these are two different changes but given that we're just changing the format of them, I'm assuming this will not be an issue to have them in one PR.
Had to add PlayerSteps into RIC since we're using enums for Player.step and …
> Refactor of RIC functions

- config/splat.us.ric.yaml
- include/entity.h
- src/ric/345EC.c
- src/ric/ric.h
This appears to be an entity updating function unique to RIC. I do not know what it is for yet.
Main reason for doing it is that it has rodata and the file it is in currently requires a rodata padding to be present. Having this one working and parsing the rodata into it means we can move the padding, and once we finish everything in this file, we will be able to remove the padding entirely.
> Decompile RIC func_8017091C

- src/dra/4A538.c
- src/dra/dra.h
If there's a better place to put the macros let me know,
The linter doesn't like it when the following macros are formatted like this : 
`#define GET_RED(x) ((x) & RED_MASK)`
as it changes them to this : 
`#define GET_RED(x) ((x)&RED_MASK)`
(removes the spaces around the `&` operator)
It's probably not configured for it as it's not happening to the `|` operator.
> Decompile DRA func_800EA720

- tools/function_finder/function_finder_psx.py
The point of this is to be able to get results only for what you want to work on. e.g:
```
python3 ./tools/function_finder/function_finder_psx.py --keywords libsnd libspu --no-fetch
| Ovl    | Function               |   Length |   Branches | Jtbl   | WIP   | %   |
|--------|------------------------|----------|------------|--------|-------|-----|
| libspu | _spu_FgetRXXa          |       23 |          3 |        |       |     |
| libsnd | SpuVmGetProgPan        |       28 |          3 |        |       |     |
| libsnd | SsUtGetDetVVol         |       30 |          3 |        |       |     |
| libsnd | _SsSndReplay           |       32 |          1 |        |       |     |
| libsnd | SpuVmGetSeqVol         |       33 |          1 |        |       |     |
| libsnd | SpuVmSetProgPan        | …
```
> Allow function_finder to filter on keywords

- Makefile
Re-generate symbols for `build/us/ric.map`. Also I moved the `--no-default` as it was previously ignored.
> Fix reporting for the RIC overlay

- src/pc/sdl2.c
I noticed the sound test app flashes when running on WSL2. This is due to `MyPutDispEnv` continuously calling `SDL_SetWindowSize` even when the parameters are the same as the previous frame.
> Fix window flashing on WSL2

- CMakeLists.txt
- Makefile.pc.mk
- src/pc/plat_unix.c
- src/pc/plat_win.c
- src/pc/psxsdk/libapi.c
- src/pc/psxsdk/libcard.c
- src/pc/sotn.c
Reduce the amount of `#ifdef` by abstracting platform specific code into ad-hoc C files that can be linked and swapped.
I trimmed down `libapi.c` and used the `My`/`my_` pattern for those specific PSX API calls. The new `plat_unix.c` contains the usual code, while `plat_win.c` contains placeholder functions waiting for an implementation. I have no rush to do so because I have yet to test if the unix version works.
I removed from `sotn.c` and `libcard.c` any reference to SDL, which is now self-contained in `sdl2.c`.
> Reduce _MSC_VER footprint

- include/entity.h
- include/unkstruct.h
- src/ric/24788.c
- src/ric/ric.h
Some entity, don't know what. There seem to be a lot of entities that just use 7C and 7E from the `ext`, might be something we think about unifying in the future.
> Decompile RIC func_80161FF0

- src/st/sel/3642C.c
Quick win. It is obviously inspired by #926 , so thanks @ser-pounce to have decompiled that function!
> SEL func_801B78BC

- include/entity.h
- src/st/no3/48A84.c
Surrounding code also seems to use the same entity struct
> Decompile NO3 func_801CC820

- include/game.h
- src/dra/6D59C.c
- src/dra/menu.c
- src/pc/sdl2.c
In the absence of `RenderingPrimitives` I had to make some assumptions.
Changelog:
* Title screen leaves are transparent
* Title screen fading-in and fading-out now working
* HUD no longer appearing black
* HUD no longer visible in the menu
> Primitive rendering fixes

- config/splat.us.ric.yaml
- include/game.h
- include/primitive.h
- include/unkstruct.h
- src/ric/21250.c
- src/ric/2A060.c
- src/ric/ric.h
Several things with this one.
1) In order to determine what this actually was, I needed to extract Richter's subweapon definitions. I decided, at least for now, to add that extraction for RIC, using the `assets.py` script.
2) In order to match this function, we need a new Primitive, which is similar to the existing one (and FakePrim) but has a few totally incompatible fields. Most importantly, we have s16's at offsets 0x0C and 0x0E, which don't match either of those. Therefore, I introduce a new primitive that I am, at least for now, calling PrimLineG2, since this is the first time we're using LineG2, and is also the first use of this struct, so those may be connected. If a different primitive is found using these fields, we can rename this.
3) Recognizing that we now have 3 different …
> Decompile RIC EntityHydroStorm

- src/dra/86ECC.c
- src/ric/21250.c
- src/ric/2C4C4.c
- src/ric/ric.h
I did the DRA version of the rebound stone a little while ago; this one is quite similar.
The rebound stone line is drawn using a series of PRIM_LINE_G2 primitives. It turns out that the new PrimLineG2 variant in `primitives.h` matches perfectly. The DRA version was using `LOH()` macros, but now it is clear that we don't need that, now that we understand the alternate primitive. It's very cool to find multiple places in the code using this struct as an alternative to the normal Primitive.
This also has two identical helper functions, so I have renamed those to match the DRA versions as well.
> Decompile RIC EntitySubwpnReboundStone

- Makefile
- config/splat.us.ric.yaml
- tools/splat_ext/spritesheet.py
A side-project I've been working on that helped me understanding some structures that are now a bit better documented in #1034 . Richter sprites are extracted as usual. Doing `python3 tools/splat_ext/spritesheet.py decode disks/us/BIN/ARC_F.BIN assets/arc alucard disks/us/BIN/F_GAME.BIN 1` can extract Alucard sprites too. There is no repacking yet as I want to avoid using splat for this one.
> Allow spritesheet to be extracted from the CLI

- src/st/mad/EDB8.c
This is just a duplicate function found from other overlays. It is part of a much bigger piece of work that depends on this.
I did not de-duplicate it due to `D_801997D8` and similar symbols where I yet need to find a common pattern to.
> MAD func_801908DC

- Makefile
- config/splat.us.main.yaml
- config/symbols.us.main.txt
- include/include_asm.h
- src/main/main.c
- src/main/psxsdk/libc/sprintf.c
- src/main/psxsdk/libcd/bios.c
- src/main/psxsdk/libcd/sys.c
- src/main/psxsdk/libgpu/sys.c
- src/main/psxsdk/libsnd/seqinit.c
- src/main/psxsdk/libspu/spu.c
I feel like getting all the rodata migrated will make it easier to update splat (also makes it easier to match functions that use rodata).
> Migrate .rodata to functions for main.exe

- include/game.h
- src/dra/5087C.c
- src/pc/sotn.c
This. It still misses the texture and I do not know what the green lines are about. All the stuff within the `#else` and `#endif` are placeholders that will hopefully be fixed later on the same way.
To get the same result from the screenshot I had to use the [func_800F1B08](https://decomp.me/scratch/nW7lV) scratch, comment  `g_CastleMap[i] = 0;` from `InitStatsAndGear` and use the following to read the map from a memory card's save:
```c
if (!FileRead(LoadMemcardSave, "memcard1.mcd")) {
WARNF("unable to correctly load the save file");
}
```
```c
s32 LoadSaveData(SaveData* save);
bool LoadMemcardSave(FILE* f) {
const int slot = 0;
SaveData save;
fseek(f, 0x2000 + slot * 0x2000, SEEK_SET);
fread(&save, sizeof(SaveData), 1, f);
return LoadSaveData(&save) == 0;
}
```
> Render the explored castle map

- src/main/psxsdk/libsnd/libsnd_i.h
- src/main/psxsdk/libsnd/seqread.c
- src/main/psxsdk/libsnd/vs_vtbp.c
This one doesn't match locally, I thought I'd post it to see if anyone spots the issue. https://decomp.me/scratch/t1MU2
I see this difference which doesn't make any sense to me
```
python3 ./tools/asm-differ/diff.py -mow3 --overlay main _SsSndSetVabAttr
1848:    nop                                         513 1848:    nop                                                                                 
>      .rodata+0x228                                                                                
184c:    move    a0,s1                            |  515 184c:    andi    a0,s1,0xff                                                                  
1850:    jal     SsUtSetReverbDepth                  515 1850:    jal     SsUtSetReverbDepth …
```
> _SsSndSetVabAttr

- include/game.h
- src/dra/843B0.c
- src/st/dre/13E18.c
- src/st/dre/succubus.c
- src/st/no3/377D4.c
- src/st/no3/48A84.c
- src/st/no3/56264.c
- src/st/no3/564B0.c
- src/st/np3/3246C.c
- src/st/np3/36990.c
- src/st/np3/44DCC.c
- src/st/np3/48238.c
- src/st/np3/490E8.c
- src/st/np3/4997C.c
- src/st/np3/49BC8.c
- src/st/np3/49F98.c
- src/st/nz0/33FCC.c
- src/st/nz0/43708.c
- src/st/nz0/43F9C.c
- src/st/nz0/44EAC.c
- src/st/nz0/45F2C.c
- src/st/nz0/4672C.c
- src/st/nz0/47958.c
- src/st/st0/2C564.c
- src/st/st0/2DAC8.c
Due to the discovery of the 0x100 entity flag in EntityDraculaFinalForm, I have gone ahead and created the #define for 0x100 being FLAG_DEAD. I have also searched the codebase for the string `flags & 0x100` and `flags |= 0x100` and made suitable replacements. There are likely other places that use the 0x100 flag which use different syntax, and those are not changed, but hopefully we can clean those up over time as we discover them.
Nice to expand our knowledge of the different available flags!
> Create and use entity flag FLAG_DEAD

- src/dra/692E8.c
- src/dra/843B0.c
- src/dra/dra.h
- src/ric/20920.c
- src/ric/21250.c
- src/ric/ric.h
While attempting to trace the process of an action in the game, I noticed that the main state machine in EntityAlucard which dispatches the functions for each player state was still using numerical `case` statements. I cross-referenced the `PlayerSteps` enum in `dra.h` to the steps in the function, and swapped in all the enum names. I also gave proper names to unk24 and unk25, deconflicting this in the Alucard and Richter player step lists.
Finally, I noticed that EntityAlucard has routines for steps 48-50, which did not have enum members, so I added those. We'll have to examine what they do.
> Use player step enum in EntityAlucard

- Makefile
- Makefile.psx.mk
- config/check.hd.sha
- config/splat.hd.tt_000.yaml
- config/undefined_syms.hd.txt
- src/servant/tt_000/10E8.c
- src/servant/tt_000/608.c
100% decompiled.
`US` adds some padding to have the file exactly 40KB long. The HD version does not add any padding, hence why I ended up producing `tt_000_raw.bin`. I would have used just `tt_000.bin` as a name as found in `disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_000.bin`, but on Windows-based file system it would collide with `TT_000.BIN` due to the OS having case insensitive names.
I modified `make clean` as I found annoying that `VERSION=hd make clean` would wipe out `us` build stuff.
The only different function in HD is `ProcessEvent`, which has a weaker check. Another hint suggesting HD being older than US.
`s32 _unused[26];` added enough padding in the bss section to get an :ok: . I am pretty sure it is unused data because the final binary is not aligned by any power of 2.
> Add TT_000 from the HD version

- Makefile.psp.mk
I improved the PSP Makefile to always remove `*.post.c` regardless if the compiler fails or succeeds. This also helps when invoking `differ` on a broken build.
The permuter uses the last Makefile line to create a `compiler.sh` script used to make a bunch of iterations. Previously it was using `rm $<.post.c || true` as compiler. Now that I compacted everything into a single line it can at least import a C file. The produced `compiler.sh` is still wrong  as it cannot properly take in consideration the `mwcpp.py` tool and the parameters to pass to it.
---
Before this fix:
```bash
$ ./import.py sotn-decomp/src/servant/tt_000/10E8.c sotn-decomp/asm/pspeu/servant/tt_000/nonmatchings/10E8/func_80171ED4.s
Compiler type: gcc
Function name: func_80171ED4
Compiler: python3 tools/mwcpp.py {input} -o …
```
> Improve permuter behaviour with the PSP build

- config/splat.pspeu.tt_000.yaml
- config/symbols.pspeu.txt
- include/psxsdk/libc.h
- include/servant.h
- src/servant/tt_000/10E8.c
- tools/mwcpp.py
- tools/mwcpp_test.py
- tools/requirements-python.txt
Having `platform: psx` will not correctly disassemble PSP functions with opcodes that are not part of the R3000 (the PSX CPU) architecture. These functions would be disassembled by Splat as a bunch of `.word 0xBLAHBLAH`. 
Changing the platform to `psp` introduces all sort of new challenges. Function prototypes needs to be declared earlier. But also the MWCC compiler will not accept the `%lo` and `%hi` dialect from GNU AS. There were some patches on `mwcpp.py` to use `la SYMBOL_NAME` that would expand into a `lui / addiu` combo. But even though symbols needs to be declared like function prototypes at the top of the file. This is simply not feasible on bigger overlays.
As a solution to the problem above, I replaced the existing patches by converting instructions into `.word`. The overlay …
> Use PSP platform to disassemble PSP overlays

- src/weapon/w_049.c
My last PR was for weapon 15, this is the same function for weapon 49.
Substantially similar; interesting that this one uses a switch on the self->step while the other one just had an `if step == 0`.
Otherwise nothing much of interest here. Going to continue to leave things as externs until each weapon is done.
> Decompile weapon 49 func_ptr_80170014

- src/dra/6D59C.c
I'm working on tracing the logic involved in using weapons. `func_8010EDB8` is a core part of that process.
I noticed a small improvement that could be made to the control flow, removing one `goto` statement.
This function could use more work on its overall control flow (there are so many uses of `goto`), but even a small improvement is still an improvement.
> Small logic cleanup on func_8010EDB8

- Makefile
- tools/sotn-disk/cue.go
In CUE files `FILE` is a stateful, global declaration that applies to all following `TRACK`s. `sotn-disk` was treating `FILE` declarations as `TRACK` delimiters which would result in incorrect parsing of CUE files with a single `FILE`, but multiple tracks.
Now when reading a `FILE` declaration, the path is stored and processing continues. A `TRACK` declaration will use the previously defined path, and if a previous track had been started, append that previous track to the list.
This also builds `sotn-disk` using the local repository instead of pulling the latest commit from GitHub. The target depends on `sotn-disk` sources and will rebuild as necessary (or with `make ~/go/bin/sotn-disk`).
As an aside, [pull/232](https://github.com/Xeeynamo/sotn-decomp/pull/232) ran into this same error, …
> Support Single BIN CUE Files

- include/game.h
- src/dra/dra.h
- src/ric/ric.h
- src/weapon/w_016.c
This is mostly just another weapon function.
However, because this references PLAYER.step, we want to use the PlayerSteps enum. This enum is in `dra.h` and therefore inaccessible to weapon functions.
I ran into this problem a while ago dealing with ric.h not having access to the steps, and just duplicated PlayerSteps. Now that we have a third place, we instead move PlayerSteps to `game.h`, and adjust `ric.h` to only use the steps that we need to override. This seems like the most sustainable solution.
> Decompile weapon 16 EntityWeaponAttack

- config/symbols.us.weapon.txt
- src/weapon/w_021.c
As noted in the comment, this is closely related to BottomCornerText, which exists in the overlays. It shows the text boxes in the lower left and lower right corners of the screen (an item you picked up, an enemy you encountered, etc).
I'm not sure how this is triggered in relation to food (I'll see when I decompile the caller), but there it is. The logic is weird since it parses characters two at a time.
I tried to make a symbol definition for this function, but it didn't work. Leaving my attempt in place to show what I did; I can remove it if desired, or do whatever is needed to rename functions in the weapon overlays. Anything works.
> Decompile weapon 21 helper function

- src/weapon/w_037.c
Not really certain what this one does. Given that weapon 37 is for the short sword and jewel sword, I wonder if it's related to the colorful particles that come out when you swing the jewel sword. I'm sure we'll learn more as we decompile the other functions in the overlay.
> Decompile weapon 37 helper 8017ADF8

- config/symbols.us.stcen.txt
- config/symbols.us.strwrp.txt
- src/st/cen/11280.c
- src/st/collect_heart_vessel.h
- src/st/dre/173C4.c
- src/st/mad/EDB8.c
- src/st/no3/41C80.c
- src/st/np3/394F0.c
- src/st/nz0/39908.c
- src/st/rwrp/A59C.c
- src/st/wrp/861C.c
This follows the model of  #[`collect_hearts.h`](../blob/master/src/st/collect_heart.h) to reuse the `CollectHeartVessel` implementation across stages that use the same implementation.
This adds implementations for CEN and WRP as well.
> Shared `CollectHeartVessel` Implementation

- src/weapon/w_037.c
- src/weapon/w_048.c
- src/weapon/w_049.c
- src/weapon/w_050.c
After decompiling `func_107000_8017B0AC`, I moved on to more weapon helper functions, and was surprised to find several more copies of nearly identical functions. The only difference between these is the fractional constants applied to the outPoint results (for example, some use 2/3, others use 3/4, and others still use 1/2).
Given the fact that these are all substantially the same, we could probably do some de-duplicating by pulling in a header file, but for now I'm decompiling each one in place, so that we can have all the functions done.
I believe this is all of the ones that match this structure; hopefully I didn't miss any!
> Decompile duplicates of weapon helper

- src/weapon/w_006.c
- src/weapon/w_007.c
- src/weapon/w_013.c
- src/weapon/w_050.c
`func_107000_8017ADF8` is already in the repo and decompiled. I found that there are several duplicates of this function, so this PR decompiles all of them.
The only difference between the copies is 1. The address of the data array, obviously and 2. the assignment to the `size` variable. Some duplicates use 4 and 6, others use 2 and 3. Otherwise they're exactly the same.
This is the only heavily-duplicated weapon helper function remaining. I have decompiled all of the helper functions (the ones that are unique to the weapon they're part of, rather than being in the standard structure like `func_ptr_801700XX`) and will be doing PRs for each of them in sequence.
> Decompile duplicates of weapon primitive helper function

- src/weapon/w_026.c
- src/weapon/w_028.c
These two functions are extremely similar so I am doing them in one PR.
Not sure what they actually do, the call to LoadImage is a bit surprising. This is used for the Skull Shield and Shaman Shield; I don't know what they have in common.
> Decompile pair of duplicated weapon helper functions

- config/symbols.us.weapon.txt
- src/dra/7A4D0.c
- src/dra/dra.h
- src/dra/loading.c
- src/pc/sotn.c
Based on Sozud's scratch (https://decomp.me/scratch/zVBXP), I got the function to match, and then confirmed that it also matches on PSX.
I also discovered a few improvements, especially in changing `D_8016FCC0[entityId];` to instead be `((PfnEntityUpdate*)FAMILIAR_PTR)[entity->entityId - 0xD0];`
While I was at it, I also updated the D_80170000 variable from a void* to be g_ServantDesc, just like we have in the servant overlay. The ServantDesc struct only exists in servant.h, so we update that as well.
Finally, we move g_Weapon to not be at 80170000, since it doesn't belong there.
> Update func_8011A4D0 to match on PSP

- src/weapon/w_041.c
Very neat to solve this with the help of the PSP version! I couldn't solve this without it, so this is a cool development. Hoping to keep benefiting from that!
This is also the final helper function in the weapons. All other functions in all the weapon overlays are part of the main Weapon struct that holds the set of several pointers to call.
> Decompile weapon 41 helper 8017A994

- src/st/mad/EDB8.c
Every other stage uses the same implementation of
`CreateEntitiesToTheLeft`, but MAD's version does not loop through all entities which may be in range, it finds the first, and depending on flags may create it, the array pointer is updated and no other entities are considered. This function is used when scrolling left, meaning if multiple entities fall within the scroll delta, only the first will be created which might have some interesting properties.
> Decompile MAD CreateEntitiesToTheLeft

- config/symbols.us.stcen.txt
- config/symbols.us.strwrp.txt
- src/st/cen/11280.c
- src/st/cen/1B274.c
- src/st/cen/D600.c
- src/st/dre/173C4.c
- src/st/entity.h
- src/st/mad/EDB8.c
- src/st/no3/41C80.c
- src/st/np3/394F0.c
- src/st/nz0/39908.c
- src/st/rwrp/14590.c
- src/st/rwrp/8DF0.c
- src/st/rwrp/A59C.c
- src/st/sel/3410C.c
- src/st/st0/31CA0.c
- src/st/wrp/861C.c
This organizes funcitons believed to be originally found in `entity.c` into an equivalent `entity.h` based on the research of @Xeeynamo:
* `DestroyEntity`
* `DestroyEntitiesFromIndex`
* `AnimateEntity`
* `PreventEntityFromRespawning`
Includes `entity.h` in place of stage implementations or ASM.
> Refactor entity.h Functions

- config/symbols.stmad.txt
- src/st/mad/15520.c
- src/st/mad/EDB8.c
- src/st/mad/mad.h
When decompiling MAD TestCollisions in my last PR, I noticed that the call to BottomCornerText was going to func_80198BC8 in MAD, which was not yet decompiled.
The duplicates report indicated that func_80198BC8 was a duplicate of func_97000_8017AB54, a weapon function that I decompiled a few weeks ago.
I copied the code for that function into here, and renamed it to BottomCornerText to match the other overlays, even though it's not the exact same code as is used in other overlays.
> Decompile MAD BottomCornerText

- tools/decompile.py
When using the `dec` script, it is possible to select a function where there are multiple functions sharing a name. The test case I had for this was `EntityEquipItemDrop`. If you run `dec EntityEquipItemDrop`, it will tell you that there are 4 occurrences of functions with that name, and list the four, telling you to re-run with -n or -f to specify which.
If you choose to specify option #0, with `dec EntityEquipItemDrop -n 0`, then the number_occurence variable will be set to zero. But the if-statement `if number_occurrence` fails, because the value is zero, which is parsed as False. Decompilation therefore fails, as if you had not passed `-n`.
This change explicitly tests for None, so that zero is a valid selection.
> Fix zero-related bug in decompile.py

- include/log.h
- src/pc/log.c
- src/pc/sotn.c
Add colours to the various logs to make sense out of all the produced noise. Also gets rid of the square brackets and use a nicer column separator. Don't mind the error log being mis-labeled. My hunger for copy&pasting code consistently betrays me.
but most importantly groups the logs to avoid spamming the same one for every frame. The log count keeps getting updated on the left-hand side of the log, replacing the beginning of the path (almost never relevant). If the log is old, the logging function will go back, update the line and go back down.
It is a tad bit slower than the original implementation, but logs are never meant to be seen anyway, especially debug logs. I used a relatively fast hashing function paired with a dictionary to avoid unnecessary loops. There are two hashes. …
> Nicer logs

- config/splat.us.main.yaml
- src/main/psxsdk/libgte/patchgte.c
I think this file is all handwritten asm
patch_gte
https://gist.github.com/sozud/f25a15fe190fc8fa77b59b2278de4d85
func_8001929C
https://gist.github.com/sozud/27df133a0207fa732991b0786ee2f34c
func_8001929C is the code used to patch the bios. The sequence
```
/* 9A3C 8001923C B0000A24 */  addiu      $t2, $zero, 0xB0
/* 9A40 80019240 09F84001 */  jalr       $t2
/* 9A44 80019244 56000924 */   addiu     $t1, $zero, 0x56
```
looks like a bios call to me and I'm not sure this can be generated by a compiler? Scratch here
https://decomp.me/scratch/TlFnw
> patchgte to asm

- include/entity.h
- src/weapon/w_028.c
- src/weapon/w_029.c
This one was a beast, but nice to get it working.
This seemed to match the same entity extension as weapon 29. Weapons 28 and 29 are both shields, so I decided to rename the Weapon29 struct to be Shield instead. We will see if it continues to match for the future shields.
This had a ton of FIX(), enums, #defines, etc, so hopefully I got them all :)
> Decompile Weapon 28 shield spell

- include/entity.h
- src/weapon/w_028.c
Secondary function for the Skull Shield. Gets spawned by the ShieldSpell that just got merged.
I also noticed too late that my previous PR reverted the update to mwccgap since I hadn't updated that; this PR includes a fix to that accidental revert.
> Decompile Weapon 28 func_ptr_80170024

- include/game.h
- src/dra/75F54.c
- src/dra/dra_header.c
The Medusa Shield's laser-beams use this function for finding enemies to target (I think).
I was reviewing this function and noticed the awkward line `if ((arg2 << 0x10) != 0) {`, and realized that means `arg2` should be `s16`. It matches, so I think this is right.
Named it facingLeft since that's what is used in the call that I have so far. The function graphs indicate that there are 3 functions that use this one (none decompiled yet), so we will see if this shifts as we discover more. For now, I think this change makes the most sense.
> Fix args for func_80118B18

- src/pc/str.c
Now with a much faster start-up
> Fix AnsiToSotnMenuString to not spam logs

- src/pc/sdl2.c
This allows the fade-in / fade-out effect from `func_801027C4` and the content from `DrawEntitiesHitbox` to be rendered on screen.
The fade-in is a bit weird, it fades out to white instead of black. I doubt the rendering is accurate at the moment, but better than not showing anything.
> Add TILE rendering to SDL2 DrawOTag

- CMakeLists.txt
- src/pc/pc.h
- src/pc/sotn.c
- src/pc/stages/stage_dummy.c
- src/pc/stages/stage_loader.c
- src/pc/stages/stage_loader.h
- src/pc/stages/stage_sel.c
- src/pc/stubs.c
- tools/splat_ext/assets.py
I had to cherry-pick some existing changes from another branch, but that part is tested and working.
For the blueprint stuff, I changed the fields from the strings `"TRUE"` and `"FALSE"` to native JSON boolean values `true` and `false`. That made things much easier to parse.
The parsing mechanic is straightforward. I'd like to have @bismurphy review on the blueprint parser and asset changes specifically.
One of the blueprints in action:
> Add blueprint support

- src/st/st0/30030.c
- src/st/st0/34908.c
- src/st/st0/st0.h
One duplicate and one near-duplicate.
`func_801B101C` ([decomp](https://decomp.me/scratch/K87Ql)) is listed as a 96% match of `func_801B76F0` but it seems to be using a slightly different Dialogue struct.
> Two small ST0 functions

- include/entity.h
- src/st/np3/4B018.c
A relatively simple function. The call to func_801CD78C necessitated the prior PR, so now that that one is in, this one can go in smoothly.
> Decompile NP3 func_801CDAC8

- .github/workflows/picci.yaml
- CMakeLists.txt
- src/main/psxsdk/libsnd/libsnd_i.h
- src/main/psxsdk/libsnd/ssstart.c
- src/pc/psxsdk/libsnd.c
- src/pc/psxsdk/libspu.c
This makes changes to allow libsnd/libspu to compile when WANT_LIBSND_LLE is set. If turned on it will immediately crash due to trying to write to the SPU. A build is added to make sure it's compiling.
> Conditionally compile libsnd

- tools/function_finder/function_finder_psx.py
We have now fully decompiled every function which had a DECOMP_ME_WIP comment, and we do not expect to ever have a need to add one in the future.
Therefore, the function finder can be simplified by removing the process of searching for these.
With no DECOMP_ME_WIP strings, `get_c_files` will never append anything to `files`, so it always returns an empty list. We can therefore remove the function.
With `c_files` always being an empty list, iterating over it will do nothing, so we can remove `c_files` and the entire block of `for c_file in c_files`.
Those are all the changes being made here, pretty simple.
> Deprecate the use of DECOMP_ME_WIP comments

- include/psxsdk/libapi.h
- src/main/psxsdk/libgs/gs_007.c
- src/main/psxsdk/libgs/gs_008.c
- src/main/psxsdk/libgs/gs_009.c
`GsInitVcount`, `GsGetVcount`, `GsClearVcount` were all small wrappers around calls to respective root counter functions using the vsync counter spec. This provides implementations for all, replacing the previous ASM imports.
> Decompile `libgs` Wrappers

- src/st/np3/3246C.c
A simple function, but a weird one.
Does a lot of odd stuff with LOW on the x coordinate (and therefore also y coordinate) of a Primitive.
It's possible that these are weird compiler optimizations (kind of like the one that does the thing with animation frames on Entities, where it loads both animation values to compare them), but hard to say for now. Hopefully with it decompiled, the research to identify what this is actually doing can come in the future.
> Decompile NP3 func_801B3D24

- src/dra/42398.c
- src/st/st0/30030.c
Found this function which had a NON_MATCHING.
I'm getting pretty good at finding PSP functions now, so finding the PSP told me that this was an if-block, not a ternary operator.
PSP also indicated that some of the other lines were using multiple-assignment, rather than a sequence of individual assignments, so I made those changes too.
As usual, I don't really know what these do, but it's nice to have pure matches now.
Now the only functions left with NON_MATCHING are RenderEntities and RenderPrimitives.
> Rewrite DRA and ST0 gpubuffer function to remove NON_MATCHING

- Makefile
- Makefile.psx.mk
This updates the Makefile so that targets which depend on phony targets
(like `*_dirs`) have direct dependencies on those targets rather than
relying on transient dependencies from dependent targets. Other targets
explicitly create parent directories for their files.
This resolves #739, making it possible to using make-4.4 to build in parallel.
> Fix Directory Creation Dependencies in Makefile

- tools/sotn-assets/build.go
- tools/sotn-assets/main.go
Attempt to fix the vertical entity layout sort in https://github.com/Xeeynamo/sotn-decomp/pull/1343. There isn't nearly enough data yet to say with certainty that this is how it was done. For example I see this run of equivalent y values in no3 that seems to break any conceivable pattern:
```
xxd -c10 -s0x4536 -l1960 disks/us/ST/NO3/NO3.BIN
...
00004ba8: 8000 d000 4d00 9000 0000  ....M.....
00004bb2: 0001 d000 1b00 7100 0000  ......q...
00004bbc: 7f05 d000 1900 7300 0000  ......s...
00004bc6: bf03 d000 1900 7200 0000  ......r...
00004bd0: 0006 d000 1b00 7100 0100  ......q...
00004bda: 8006 d000 4d00 9000 0000  ....M.....
...
```
> Asset manager next

- Makefile
After building for all supported architectures `make format` was taking around 30s. This commit includes various changes which get that down to around 3½s on the same machine.
This changes the `format` target in a few ways:
* filters out files generated by CMake
* runs `clang-format` in parallel
* breaks `format` into 3 separate targets which can be run in parallel
When building the PC version cmake creates a file to test compiler features. This file is picked up by the pattern which matches files for `clang-format`. This file took around 20s, filtering it out brought total format time to around 10s.
Instead of passing a list created by a `find` command directly as the args to `clang-format` the list is now passed to `xargs` which runs several processes in parallel, each looking at 10 …
> Speed Up `make format`

- src/weapon/w_013.c
Someone in the Long Library discord was asking about Heaven Sword (especially its special attack) so I'll go ahead and decompile that next.
This initial function appears to reveal that Heaven Sword doesn't follow the main Weapon struct. I'm going to keep using it until the weapon is done, so we can get a better picture of what the mismatching fields are. All the struct members are the same size, they're just different names.
> Decompile heaven sword func_ptr_8017000C

- include/entity.h
- src/weapon/w_013.c
This one is kind of ugly in places.
It uses offset 0x84 as an s32, while Weapon uses it to hold an entity, so this forced the creation of a new ext for the heaven sword.
There is only one more function left in this file (EntityWeaponAttack), so once that one is done, I will move the whole file over to use the Heaven Sword extension.
> Decompile heaven sword func_ptr_80170008

- config/symbols.us.dra.txt
- src/weapon/w_020.c
The Karma Coin, surprisingly, has the largest EntityWeaponAttack of all the weapons. For that reason, I'm targeting it next.
It has one small other entity function, so this PR decompiles that first, prior to going ahead and decompiling the EntityWeaponAttack itself.
Otherwise, nothing too crazy special here. I imagine decompiling the Karma Coin will make it clear what this helper entity is.
> Decompile Karma Coin func_ptr_80170008

- include/game.h
- src/dra/8D3E8.c
- src/dra/90264.c
This is a relatively unimportant function, but it messes with some variables that I am interested in learning more about, so I went ahead and compared it to the PSP version.
This PR incorporates some lessons I learned from that PSP version. Most importantly, the rotPivotX and rotPivotY in Entity are signed.
I also tracked down how this entity is created, it's a bit odd since it doesn't call any entity creation function, and instead does a direct write into g_Entities to create it.
On exit, this function calls `func_8012C600`, which I will be doing a similar analysis for next.
There was a leftover rodata padding that doesn't do anything, so I removed that too.
> Minor cleanup on wolf function func_8013136C

- src/dra/5087C.c
Lots of small changes here, but ultimately this ends up rewriting the whole function.
I opened this one in PSP (it's `-O4`!) and found several differences which I corrected. I also rewrote some of the if-statements to be a bit more readable.
Kind of a weird function the way it's testing for hard-coded X and Y values. Not sure what this function actually does.
We also end up only calling `func_801042C4` once, which is a nice improvement for readability.
`func_801042C4` is not decompiled, so I'll move on to that next.
> Cleanup on func_800F24F4

- .github/workflows/validate-and-report.yml
- tools/analyze_calls.py
The new setup with RWRP sharing files with WRP means some of the assumptions made while developing analyze_calls no longer hold.
The new code adds some checks and tweaks the logic to now handle these situations. This works on my computer.
This PR is into the rwrp_merge branch, not into master, so that we can make sure that branch builds successfully without needing to rebase.
> Fix analyze calls for RWRP PR

- tools/analyze_calls.py
Iterating on this problem in master.
Now that wrp/rwrp are sharing so much code, analyze_calls is having trouble telling what functions call each other in which overlay.
I think this will resolve all the issues we have for now, but I'm sure more will appear over time.
> Attempt fixing analyze_calls build issue

- tools/function_finder/function_finder_psx.py
- tools/function_finder/helpers.py
This changes the psx function finder to compare the local and remote asm to find a match. Right now there's a lot of false positives due to name collisions. The new output looks like this:
https://gist.github.com/sozud/4eaa80c2ebb475551986b4f55d42d036
This should be off by default for the other platforms but I can't check saturn locally right now.
> Compare function similiarity in function_finder

- tools/function_finder/helpers.py
Now that @sozud has added function similarity, I wonder if it's worth including prefix matches in the results of function_finder. This would let us name a scratch ex: `EntityWeaponAttack_w_053` and have it still show up in functions.md. Thoughts?
> Idea: allow postfixing of func names

- config/symbols.us.weapon.txt.in
- src/weapon/w_052.c
The most important thing here is that D_170000_8017CBD0 is an array of f32 values. But since entry 0 is only accessed with `.i.hi`, the auto-detected symbol was `CBD2`, offset by 2, so I had to manually make the symbol for this one variable. I studied the symbols file to figure out how to declare it, and this ended up working. Now that I know how to make weapon symbols, I can start making useful names for these in the future. Not for this one though, this doesn't make any sense.
> Decompile w52 (Alucard Shield) func_ptr_80170004

- tools/dups/Cargo.lock
- tools/dups/Cargo.toml
- tools/dups/src/main.rs
- tools/tools.mk
The duplicates report has several false negatives when a function has the same name as another function which has not been decompiled. This affects overlays which share many of the same function names (e.g. `EntityWeaponAttack`).
The duplicates tool now parses the `INCLUDE_ASM` macro to extract the path and ASM file. It then uses that when determining whether or not each ASM file is actually included or not. Previously, only the function name was checked, so if any `INCLUDE_ASM` file had the target function name, it would be marked as not decompiled.
Before:
% | Decomp? | Name | Asm Path
-----|-------|-------------------------------|--------------------------------    
| 1.00 | false    | EntityWeaponAttack                  | ../../asm/us/weapon/nonmatchings/w_008/EntityWeaponAttack.s
| …
> Match Functions with Same Name in `dups`

- include/entity.h
- src/weapon/w_008.c
- src/weapon/w_009.c
- src/weapon/w_010.c
- src/weapon/w_011.c
- src/weapon/w_023.c
- src/weapon/w_024.c
- src/weapon/w_025.c
- src/weapon/w_026.c
This PR is big, but it's because these functions are almost perfect duplicates of each other. I figured it would make more sense to process them all at once than to have 9 more PRs for essentially the same function.
This basically handles the animation of holding up/putting down a shield, so it makes sense that the shields are all mostly the same.
The differences are with shields that have an effect when something hits them - this includes the Iron Shield, Dark Shield, and Herald Shield. Aside from these ones, this function is a perfect copy-paste, only requiring variables to be renamed. And with those three, it's still the same function, just with a few lines added to create their special effect. Search for "hitFlags" to see the effects on Iron and Herald, and for ext.darkShield to see …
> Decompile EntityWeaponAttack for all remaining shields

- src/weapon/w_038.c
- src/weapon/w_039.c
Decompiles `EntityWeaponAttack` for `w_038` and `w_039`. These match several other `EntityWeaponAttack` methods with the addition of a conditional call to `CreateEntFactoryFromEntity` at the end.
> Decompile w_038, w_039 `EntityWeaponAttack`

- include/sfx.h
- src/ric/2A060.c
Starting off with something simple.  Per [sozud](https://github.com/sozud)'s suggestion in #1441 , I put in a new enum for sounds.  There's only one reference to Richter's whip sound in the codebase so far.  According to my research, BO6 and RBO1 reference this ID as well.  
There's several other whip rattle sounds (0x603-0x606) immediately following the commonly heard 0x602 cue.  Unless BO6 or RBO1 uses random sound calls (like Alucard's randomized grunts), I don't believe these are referenced in the game and are unused.
> Added SFX enum and SFX_RIC_WHIP_RATTLE_A

- src/main/psxsdk/libc/memmove.c
Decompile `libc2`'s `memmove`.
> Decompile `memmove`

- tools/function_finder/helpers.py
Currently function_finder misses functions since we don't continue to fetch if there's another page of results. However just increasing the page size makes the script super slow. 
This adds caches to the zip file and result fetching to try and get this running at a reasonable speed for `weapon`. We also fetch until `next` is null and increase the page size so all the results are fetched. This runs about 12 minutes on my system now. Results look like this https://gist.github.com/sozud/69aeafcc671d6354da474db952e8afef
> Function finder fixes

- include/sfx.h
- src/dra/627C4.c
- src/dra/63ED4.c
- src/dra/72BB0.c
- src/dra/menu.c
- src/ric/2C4C4.c
- src/ric/319C4.c
- src/st/collision.h
- src/st/dre/13E18.c
- src/st/dre/succubus.c
- src/st/mad/collision.c
- src/st/no3/3FF00.c
- src/st/no3/no3.h
- src/st/np3/4F5B8.c
- src/st/np3/blade.c
- src/st/np3/slogra.c
- src/st/nz0/47048.c
- src/st/nz0/slogra.c
- src/st/sel/2C048.c
- src/weapon/w_001.c
- src/weapon/w_028.c
- src/weapon/w_042.c
- src/weapon/w_051.c
Stopping at 0x633 (`SFX_UI_SELECT`) for now, but will continue to add and update more sfx references soon.  
So far we have 51 out of a potential 736 sfx IDs (`0x8E0` - `0x600`).  
For what it's worth, the last valid sound ID I have listed in my spreadsheet is `0x8D2` found in `DRA`, `RIC`, `BO4`, `BO6`, and `RBO5` so the actual number might be 722 enum IDs, but we'll see what happens since the last sfx group in the list belongs to vabid 3.
> Added and updated SFX references 

- .github/workflows/picci.yaml
- CMakeLists.txt
- src/pc/io.c
- src/pc/pc.h
- src/pc/pl_arc.c
- src/pc/sim_pc.c
- src/pc/sotn.c
- src/pc/stages/stage_loader.c
- src/pc/stages/stage_wrp.c
- src/pc/weapon_pc.c
Use the following input endpoints `FileOpenRead`, `FileReadToBuf`, `FileAsString` and `FileUseContent`. 
There was a lot of redundant and inconsistent code scattered across all the functions responsible of opening and processing files. I also realised the purpose of some File helpers was not entirely clear, so I spent some effort to document them.
This is a small part of a bigger effort on refactoring `sim_pc.c`. I am also planning on adding support for paths such as `disk://` to load from `disks/us/`, `asset://` to load from `asset/`, `card://` to start adding support for simulated memcards and so on. This is setting the very basics to plan that out.
> Refactor File helper functions

- include/entity.h
- src/pc/io.c
- src/pc/pc.h
- src/pc/pl_arc.c
- src/pc/render_shared.c
- src/pc/sim_pc.c
- src/pc/stages/stage_loader.c
- src/pc/stages/stage_sel.c
- src/pc/str.c
- src/pc/weapon_pc.c
* forward declaration for `struct Entity` prior to `PfnEntityUpdate`
* definition guard around `VERSION_PC` in `pc.h`
* various libc includes to avoid implicit signatures
* `const` string arguments to avoid dropping a const qualifier
This cleans up most of the warnings from the cmake build. There are still a few from `libgte` and one more `const` to mutable assigment but most have been resolved.
> Miscelaneous Header Cleanup

- src/ric/2C4C4.c
sp10 isn't large enough to do `i + 8`, tested ingame and seems to look correct
> Fix crashing in RicEntityHolyWaterFlame

- include/unkstruct.h
- src/dra/5087C.c
- src/dra/627C4.c
- src/dra/63ED4.c
- src/dra/692E8.c
- src/dra/6D59C.c
- src/dra/72BB0.c
- src/dra/8D3E8.c
- src/ric/1AC60.c
- src/st/dre/11A64.c
- src/st/e_breakable.h
- src/st/e_collect.h
- src/st/init_entity.h
- src/st/mad/D8C8.c
- src/st/no3/377D4.c
- src/st/nz0/e_breakable.c
- src/st/rwrp/warp.c
- src/st/st0/27D64.c
- src/st/st0/2B0C8.c
- src/st/wrp/warp.c
- src/st/wrp_psp/e_collect.c
This is actually what I was initially going for in my previous PR.
g_zEntityCenter was almost always used as an s32, but some of the duplicates of e_collect which were scattered across overlays had weird misuses that acted like it was s16, which necessitated the use of the Multi.
Now that e_collect is unified across overlays, we can make this data field a proper s32. Nice!
The only change made in this PR is the type of this variable, and a find-and-replace to change it to not need to access the .unk element of the Multi struct anymore, since now it's just a bare s32 (but still contained in the unkGraphicsStruct of course).
> Remove Multi type from g_zEntityCenter

- src/pc/sotn.c
- src/ric/21250.c
- src/ric/2C4C4.c
- src/ric/ric.h
We have a problem where pointers across the various entity structs do not align. This causes the game to crash because it tries to reference the wrong offsets. I don't think this should be the final version of this fix but I'm putting it up for feedback.
This can be tested with this change to give the cross:
```
// Richter gets a random subweapon.
if ((g_StageId != STAGE_ST0) && (g_StageId != STAGE_NO3)) {
+                g_Status.subWeapon = SUBWPN_CROSS;
}
```
The cross spawns a transparent object behind it using the entity factory system. We go from:
EntityCrossBoomerang which creates Entity factory 5, which calls RicCreateEntFactoryFromEntity
The parent pointer there has to align with the children
```
// the parent pointer must align for anything the factory creates …
```
> Attempt to fix cross shadow

- include/entity.h
- src/ric/21250.c
- src/ric/2C4C4.c
- src/ric/ric.h
Got away from using `generic`. Only two fields are used, but unk8C was taken in the main Vibhuti crash, so can't reuse it.
Trying to start using the `s32 : 32` syntax to indicate unused fields moving forward, may help with figuring out how to handle the problem of `Ext` and its mysteries.
> Document RIC Vibhuti crash cloud

- include/common.h
- include/entity.h
- src/dra/7E4BC.c
- src/st/mad/15520.c
- src/st/np3/4D540.c
- src/weapon/w_027.c
`#ifdef` ugliness, but there is not much we can do if some of the `ext` structs use 64-bit pointers. With _Static_assert we can ensure, at compile time, that structs are aligned for `g_api.PlayAnimation` to work correctly.
I removed a bit more of `ext.generic` here and there too.
cc. @bismurphy our weapon blacksmith xD
> Enforce ext.*.anim alignment

- include/entity.h
- src/st/no3/377D4.c
- src/st/np3/32830.c
- src/st/np3/e_init.c
Lots of little changes here. Getting away from using `ext.generic`, using various enums/macros, using `prim` instead of `POLY_GT4`, making variables have useful names, etc.
Also, these  functions both match on PSP now.
One interesting thing is that these functions don't overlap in their use of the `ext`, so I had them share one. Kind of interesting.
> Modernize NO3 cavern door code

- config/splat.us.stnp3.yaml
- include/entity.h
- src/st/e_collect.h
- src/st/no3/3FF00.c
- src/st/no3/no3.h
- src/st/np3/32830.c
- src/st/np3/363FC.c
- src/st/np3/np3.h
- src/st/nz0/311C0.c
- src/st/nz0/gaibon.c
- src/st/nz0/nz0.h
Main changes here involve renaming the Ext member from `et38` to `wargpuff` which seems more descriptive.
Also added entity ID numbers across the overlays, to be used in the function right before the warg puff function, which spawns the warg puffs with a call to `CreateEntityFromEntity`.
> Improve EntityWargExplosionPuffOpaque

- include/entity.h
- src/st/no3/564B0.c
- src/st/np3/49BC8.c
A minor PR that only aims to give a meaningful name to two of the unknown variables in the `ET_ZombieSpawner` struct:
- `spawnDelay`: Number of frames until the next time the Zombie Spawner will attempt to spawn another zombie
- `spawnSide`: Which side of the player the Zombie Spawner will attempt to spawn the next zombie (zero for left, non-zero for right)
> Rename unknown members of Zombie Spawner struct

- include/entity.h
- src/st/no3/48A84.c
- src/st/no3/no3.h
Thanks again @joshlory @bismurphy for the help!
> EntityStrongWargDeathBeams

- Makefile
- src/dra/8A0A4.c
- src/ric/24788.c
- src/ric/26C84.c
- src/ric/2C4C4.c
- src/ric/319C4.c
- src/st/e_collect.h
- src/st/e_red_door.h
- src/st/e_stage_name.h
- src/st/entity_explosion.h
- src/st/entity_intense_explosion.h
- src/st/entity_message_box.h
- src/st/entity_relic_orb.h
- src/st/no3/516B4.c
- src/st/np3/44DCC.c
- src/st/np3/49F98.c
- src/st/nz0/e_bloody_zombie.c
- src/st/popup.h
- src/st/prim_helpers.h
- src/st/st0/2B0C8.c
- src/weapon/w_023.c
- src/weapon/w_027.c
- src/weapon/w_029.c
- tools/lints/sotn-lint/src/drawmodes.rs
- tools/lints/sotn-lint/src/main.rs
A few updates that didn't make it into the first round:
* masks are now identified and expanded
* AND-EQUALS and OR-EQUALS are supported
* `sotn-lint` is run before `clang-format` to avoid having to run the `format-src` target twice to catch line breaks
* `.h` files are included in `sotn-lint` since they are being used for shared code
* `sotn` lint ignores the `mednafen` directory
> Enchanced Draw Mode Lint

- include/psxsdk/libgte.h
- src/main/psxsdk/libgte/reg03.c
Based this off other Josh's work on https://decomp.me/scratch/ncrbI
Noticed there was already a define in `libgte.h` for Vector0 which I've used, but also filled out the other two.
Hope this is ok for a first PR 😄 
Let me know if anything needs changing.
> Decompile `SetVertex` functions in `reg03.c`

- include/psxsdk/libgte.h
- src/main/psxsdk/libgte/reg03.c
* SetRGBfifo
* SetIR123
* SetIR0
* Named this what I think is the same function [gte_lddp](https://github.com/Xeeynamo/sotn-decomp/blob/20652c255c368a112ea9de6c09474b1a3be59e16/src/pc/psxsdk/PsyCross/src/gte/psx/inline_c.h#L144) in Psycross
* SetSZfifo3
* Named this what I think is the same function [gte_ldsz3](https://github.com/Xeeynamo/sotn-decomp/blob/20652c255c368a112ea9de6c09474b1a3be59e16/src/pc/psxsdk/PsyCross/src/gte/psx/inline_c.h#L172) in Psycross
* SetSZfifo4
* Named this what I think is the same function [gte_ldsz4](https://github.com/Xeeynamo/sotn-decomp/blob/20652c255c368a112ea9de6c09474b1a3be59e16/src/pc/psxsdk/PsyCross/src/gte/psx/inline_c.h#L180) in Psycross
* SetSXSYfifo
* Named this what I think is the same function …
> Decompile remaining functions in `libgte` `reg03.c`

- src/st/nz0/st_common.c
Noticed this one was different from all the others in the way it did its GetSine and GetSineScaled.
- Rename D_80181978 to g_SineTable (to match other overlays)
- Move sine table to be right above the two sine functions that use it
- Include the .h files for the sine functions, which are identical to other overlays
> Make NZ0 sine function deduplication normal

- Makefile
- tools/make-config.py
- tools/symbols.py
As promised, a new tool to automatically generate a splat config for PSP and PSX overlays for multiple game versions. This first version will perform the following tasks:
* Create the splat config with data, rodata, text and bss sections to their right offsets
* Generate a symbol list by cross-referencing duplicate symbols
* Split the overlay by creating the correspondent C file
This tool is not currently:
* Splitting C files
* Importing shared code already decompiled
There is a lot of tech involved, especially to detect the various sections for the PSX overlays. But I will leave it to you to discover how the implementation work if you're interested. Hopefully the code is self-documented enough.
Usage examples:
* `python3 tools/make-config.py mar`
* `VERSION=jp12 python3 …
> Add tool to generate splat configs

- src/st/no3/48A84.c
- src/st/no3/no3.h
https://decomp.me/scratch/TVEAy
> Decompile `st/no3` `EntityUnkId31`

- src/st/no3/4AFF0.c
- src/st/no3/no3.h
my first decompiled function. no idea who this is but we're setting up their hitbox.
> decompile EntityUnkId4B

- tools/analyze_calls.py
In analyze_calls, we need to analyze a function's calls, and be able to track where they go. Given that a `jal` call only has a function name, it's possible for it to go to a function in any overlay. Therefore, we need to disambiguate across overlays.
We do this by identifying what overlay every function is in. This comes from the filename of the assembly file.
Since the overlay might be in, for example, asm/us/dra (a "level 3 overlay" because it has 3 directory names) or asm/us/st/cen (a "level 4 overlay") we had special logic for testing for "st".
Now that we can also have level 4 overlays in "boss" (with Maria and BO3 coming up) we need to test for those too.
While we're at it, we also only run on the "us" version's assembly files.
> Fix analyze_calls for boss stages

- src/dra/692E8.c
- src/dra/843B0.c
- src/ric/21250.c
- src/ric/2C4C4.c
- src/st/cen/DB18.c
- src/st/no3/377D4.c
- src/st/np3/32830.c
- src/st/np3/4B018.c
- src/st/np3/4D540.c
- src/weapon/w_015.c
- src/weapon/w_030.c
Minor fixes to use the enum values in `dra`, `ric`, `cen`, `no3`, `np3`, `weapon`
> Use collider values to map to enum

- src/servant/tt_001/F84.c
Ran my code for this function against the PSP assembly and fixed a bunch of places where it didn't match.
It's pretty close now, but still missing a bit.  I think it's mostly around the number of parameters and the number of temp variables as it's mostly all in the stack push/pop.
Also removing unnecessary casts.
Scratch
https://decomp.me/scratch/0Gm3x
> Various cleanup to match PSP decomp

- .github/workflows/validate-and-report.yml
- tools/dups/src/main.rs
This should prevent cases like this:
Where the nonmatching function is treated as the comparison for similarity.
After fixing:
> Ensure decompiled function is treated as the initial comparison basis in dupe report

- .github/workflows/validate-and-report.yml
Should fix issues with symbols in subsequent steps related to the use of `force_extract`
> Remove the function calls chart from CI workflow

- .github/workflows/validate-and-report.yml
I still can't reproduce the prior CI issue locally.
Steps:
* Clone repo fresh
* Follow steps from `generate-duplicates-report`
*  `make update-dependencies`
* `make extract_disk`
* `Obtain built binaries` extracting `build_us.zip` from failing job to `build/us/*`
* `make force_symbols`
* `make -j extract`
* `cd tools/dups`
* `cargo run --release -- --threshold .90 --output-file ../../gh-duplicates/duplicates.txt`
Given the suspicion is the `.ld` files I've added a step to remove those from the `build_us.zip` output before running.
After doing so and running the workflow steps from this PR, output is
duplicates.txt: https://gist.github.com/JoshSchreuder/4725784aa12ab97e37ae31d6035c0ade
> Try fixing duplicate report symbols by cleaning .ld files first

- tools/dups/src/levenshtein_hashmap.rs
- tools/dups/src/main.rs
Noticed this in the workflow output:
```
checking "../../src/boss/rbo3/create_entity.c"
Failed to match regex on line: INCLUDE_ASM(
Failed to match regex on line: INCLUDE_ASM(
```
This is because of the linting line breaks inserted to enforce column width
https://github.com/Xeeynamo/sotn-decomp/blob/master/src/boss/rbo3/create_entity.c#L6-L7
For INCLUDE_ASM lines this code checks if it contains a `;`, otherwise it will attempt to buffer subsequent lines until `;` is found to get the full INCLUDE_ASM. Also updated the regex slightly to allow for an optional line break component
Gist output: https://gist.github.com/JoshSchreuder/bf8621628640e9da96de2a565c982d00
> Fix issue with line split INCLUDE_ASM not being picked up by dups report

- src/main/psxsdk/libetc/intr.c
Removes the SOTN-specific `game.h` include from an SDK file.
> Remove SOTN Includes from PSXSDK

- src/servant/tt_002/3678.c
- src/servant/tt_002/faerie.h
This is the primary ability update function for Faerie.  The basic idea is that we some upkeep every frame, and tick down the timer. 
Once the timer has ticked down, it resets and then  searches through it's logic to figure out if the player is in a state that the Faerie  can alliviate.  If a path is found, a luck check is performed and if sucessful, the Entity ID is updated so that a different update function is called on the next update(s) to perform the action.
Note, this is not initiated from the engine, this is called from many of the update functions that the engine does call on every frame.
PSX: https://decomp.me/scratch/3ADW8
PSP: https://decomp.me/scratch/53Vc0
This should be a PSP match.
@hohle got this most of the way, I just figured out the local variables.
Co-authored-by: …
> Decompile tt_002 func_us_80173D60

- src/servant/tt_000/bat.c
- src/servant/tt_000/bat.h
- src/servant/tt_000/bat_data.c
- src/servant/tt_001/ghost.c
- src/servant/tt_001/ghost.h
- src/servant/tt_001/ghost_data.c
Adding GhostAbilityValues and BatAbilityValues structs for the ability stats by level lookup tables instead of using a multi dimension array with index defines.
> Adding structs for servant ability stat tables

- src/servant/tt_002/faerie.c
- src/servant/tt_002/faerie.h
- src/servant/tt_002/faerie_data.c
Simple follow-up to #1913. The `s32*` type (or any pointer type) already aligns with the targeted architecture. So there is no need for a `#ifdef`
cc. @Onenutmcgee
> Remove Faerie data #ifdef

- src/st/no0/e_plate_lord.c
smaller Plate Lord functions
`func_us_801D26CC`:
PSX: https://decomp.me/scratch/9qCgN
PSP: https://decomp.me/scratch/8erAA
`func_us_801D274C`:
PSX: https://decomp.me/scratch/CpoFE
PSP: https://decomp.me/scratch/Fib0r
> Decompile func_us_801D26CC and func_us_801D274C

- include/entity.h
- src/st/no0/e_plate_lord.c
PSX: https://decomp.me/scratch/3hzY4
PSP: https://decomp.me/scratch/jnXaI
I used ext.plateLordUnknown because unkAC in ext.plateLord couldn't apply. However ext.plateLordUnknown.unk80 seems to be used as an angle elsewhere while here it looks like it's used as a timer. Should I make a new ext struct for this entity ?
> Decompile `no0` func_us_801D4CAC

- config/symbols.us.tt_003.txt
- include/entity.h
- src/servant/tt_002/faerie.c
- src/servant/tt_003/demon.c
For whatever reason, the g_PauseAllowed code is stripped out of this function for PSP.
This also uses the (s16*) trick that other demon code uses for the SFX structs.  I'll circle back at refactor time to try and figure out a better way, although it's a small price to pay to use a proper struct.
Full match
// PSX: https://decomp.me/scratch/TLUnC
// PSP: https://decomp.me/scratch/GQL4q
> Decompile tt_003 func_us_80175810

- tools/requirements-python.txt
Version 1.12.1 appears to have something which broke the build, pinning for now.
https://github.com/Decompollaborate/rabbitizer/releases/tag/1.12.1
> Pin rabbitizer to 1.12.0

- src/dra_psp/67F0.c
Relatively simple one here. Only weird thing is that it deals with floats, which we're not accustomed to since the PS1 CPU doesn't have an FPU.
> Decompile PSP-exclusive DRA func_psp_090E4968

- config/symbols.pspeu.dra.txt
- src/dra/5F60C.c
- src/dra/63ED4.c
- src/dra/dra.h
- src/dra_psp/61F30.c
- src/dra_psp/67F0.c
Yet another one in sequence. As usual, a bit of tweaking for the match, but looks nice on both systems.
Very curious what the PSP sprite is. Might need to fire up my PSP version and compare side by side. As far as I know there isn't a good debugging-friendly PSP emulator out there, because it would be nice to be able to view the VRAM to see what's in the tpage.
> DrawRichterHUD matching for PSP

- include/bios.h
- src/main/psxsdk/libapi/a36.c
- src/main/psxsdk/libapi/a37.c
No idea if this is useful or necessary, but less is usually more!
> Reduce reliance on hand-coded asm for syscalls

- config/symbols.us.stlib.txt
- src/st/lib/e_stage_name.c
- src/st/lib/lib.h
PSP is completely different for these funcs so just going to do PSX for now and work on PSP separately.
Once I've worked that out on PSP I'm hopeful I can port similar changes into `wrp` `e_stage_name` for PSP too which is missing a match currently.
> Dedupe `lib` `e_stage_name`

- config/splat.hd.ric.yaml
- config/splat.hd.stcen.yaml
- config/splat.pspeu.stst0.yaml
- config/splat.us.bomar.yaml
- config/splat.us.borbo3.yaml
- config/splat.us.stlib.yaml
- config/splat.us.stno0.yaml
- config/splat.us.stno1.yaml
- config/splat.us.tt_001.yaml
- config/splat.us.tt_002.yaml
- config/splat.us.tt_003.yaml
- config/splat.us.tt_004.yaml
- include/gte.inc
- include/macro.inc
- tools/dups/src/main.rs
- tools/make-config.py
- tools/progress.py
- tools/requirements-python.txt
- tools/splat_ext/animset.py
- tools/splat_ext/assets.py
- tools/splat_ext/cmp.py
- tools/splat_ext/cmpgfx.py
- tools/splat_ext/pal.py
- tools/splat_ext/raw.py
- tools/splat_ext/spritesheet.py
Reverts Xeeynamo/sotn-decomp#2165
> Revert "Update Splat to 0.27.3"

- .github/workflows/saturn-build.yml
#2188 will fail until this is merged.
> Updated "Build saturn binaries" to use VERSION env

- Makefile
- tools/dups/src/levenshtein_hashmap.rs
Peeling the speedup and grouping bug fix off from the other changes in the `speedy-dups` PR (#2205).
Looking at the difference of size of two functions is a constant time approximation to the Levenshtein distance. Checking this prior to calculating the true edit distance provides a significant speedup without any modification to behavior.
This also fixes an issue where a "similarity" calculation (one minus the ratio of edits to size) was being returned but treated as a "distance" in some calculations. This meant that functions where grouped with the least similar function which was above the threshold instead of the most similar. This affects a few groups, like `*_EntityCutscene` where the two groups now contain functions that match more closely than before.
Some make recipes are also …
> Speed Up `dups` & Fix Grouping

- include/entity.h
- src/st/lib/e_lesser_demon.c
- src/st/lib_psp/unk_1D9E8.c
PSX: https://www.decomp.me/scratch/oWf8p
PSP: https://www.decomp.me/scratch/BzLiq
> Decompiled `lib` func_us_801BB8DC/func_psp_09255D78

- config/splat.us.stmad.yaml
- tools/symbols.py
EDIT: Approach updated, below is no longer applicable. See comments for more details.
This restores two MAD functions to the function report which went missing
Output from local:
https://gist.github.com/JoshSchreuder/c146abedc057b18d588b44446b00b596
```
| mad    | func_8018D8C8                     |      250 |         45 |        |                                                                                                    |       |     |
| mad    | func_80197B94                     |      491 |         44 | Yes    |                                                                                                    |       |     |
```
This was because since #2248 added MAD to the force_symbols extract, it was mapping 5 labels in these functions as symbols which was [causing invalid …
> Fix MAD funcs not appearing in function report

- tools/decompile.py
Check that the C path is taken from the relevant overlay.
Before:
```
$ dec func_us_801C9764
Traceback (most recent call last):
File "/<repo_path>/sotn-decomp/./tools/decompile.py", line 334, in <module>
decompile(args.function, args.number_occurrence, args.force)
File "/<repo_path>/sotn-decomp/./tools/decompile.py", line 269, in decompile
funcs = get_nonmatching_functions(asm_dir, func_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/<repo_path>/sotn-decomp/./tools/decompile.py", line 67, in get_nonmatching_functions
function = NonMatchingFunc(full_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/<repo_path>/sotn-decomp/./tools/decompile.py", line 56, in __init__
assert len(c_paths) == 1
^^^^^^^^^^^^^^^^^
AssertionError
```
After:
```
$ dec func_us_801C9764
In file included from …
```
> Fix decompile.py failing on duplicate C filenames

- tools/sotn_permuter/permuter_loader.py
I found `permute ric 182C8 RicSetSubweaponParams` strips the `s` character at the end, resulting the permuter trying to work in `sotn-decomp/tools/sotn_permuter/permute.me/RicSetSubweaponParam/`.
> Permuter loader: fix function names terminating with 's'

- config/symbols.pspeu.txt
- include/game.h
- src/dra/7879C.c
- src/dra_psp/E6A8.c
- src/st/e_mist_door.h
- src/st/entity_relic_orb.h
- src/st/get_lang.h
- src/st/lib_psp/e_shop.c
- src/st/st0_psp/3101C.c
- src/st/st0_psp/lang.c
Added a symbol / renamed this so it's clearer in code / assemblies what it's used for.
~~Also did a slight update of the LANG enum to use more "typical" 2 character ISO codes for German (DE) and Spanish (ES)~~
> Rename symbol for `g_UserLanguage` on PSP side

- config/symbols.us.bobo4.txt
- include/entity.h
- include/game.h
- src/boss/bo4/doppleganger.c
- src/boss/bo4/unk_45354.c
- src/boss/bo4/unk_46E7C.c
- src/boss/doppleganger.h
- src/boss/rbo5/doppleganger.c
- src/boss/rbo5/unk_44954.c
- src/boss/rbo5/unk_4648C.c
- src/dra/6DF70.c
- src/dra/71830.c
- src/ric/pl_utils.c
- src/st/lib/unk_3B53C.c
Matching 11 additional functions across both `BO4` and `RBO5`.
A small change to `ET_DisableAfterImage` which appears to be used for Doppleganger as well. The names and comments did not match the offsets.
Some minor cleanup for things encountered while looking for similar or matching code.
> Several More `BO4` and `RBO5` Functions

- .github/workflows/dockerfile.yaml
- Dockerfile
- tools/requirements-debian.txt
Enhance the SOTN Decomp experience with Docker. This is a full break-down of the changes:
* Enhance the instruction steps to build the image.
* Use default `ubuntu:ubuntu` user. It should map directly to 1000:1000 from the host, without messing with new users and permissions. There was a problem where the container used a mix of two users, causing various "permission denied".
* The installation of dosemu2 was broken, it is now fixed.
* The Python set-up step is now removed from the build image step and moved in a later stage. This is now done in the container itself with `make update-dependencies`.
* Added a `/sotn/.venv` overlay, so it will not conflict with the native `.venv` folder (if this is present). This allows me to use concurrently both .venv from Arch Linux and the containerised …
> Improve Docker support

- src/boss/bo4/unk_45354.c
- src/boss/bo4/unk_46E7C.c
- src/boss/doppleganger.h
- src/boss/rbo5/unk_44954.c
- src/boss/rbo5/unk_4648C.c
Most of this work was done by @PancakeFriday, Bossy Dragonfly (anon), and @joshlory. I just updated symbols based on master and applied the necessary changes for `RBO5` as well.
* `func_8010FAF4` - @PancakeFriday - https://decomp.me/scratch/0QNbK
* `func_us_801C6BA0` - Bossy Dragonfly (anon) - https://decomp.me/scratch/5m4NA
* `func_us_801C55A8` @PancakeFriday - https://decomp.me/scratch/Z2JGN
* `func_us_801C8EE4` - Bossy Dragonfly - https://decomp.me/scratch/31xdM
* `func_8010E470` - @PancakeFriday - https://decomp.me/scratch/H7nCT
* `func_8010ED54` - @PancakeFriday - https://decomp.me/scratch/CgqPe
* `func_us_801C5FDC` - @PancakeFriday - https://decomp.me/scratch/tbs1F
* `func_80111CC0` - @PancakeFriday - https://decomp.me/scratch/RSFqt
* `func_80111CC0` - @PancakeFriday - …
> Consolidating Several Decomp.me Scratches for `BO4` and `RBO5`

- .github/workflows/validate-and-report.yml
- Makefile
Duplicate check was skipped locally so you can ignore that part
https://gist.github.com/JoshSchreuder/e141eab0d4e2813d93d3213c1bf2ba6e
Now correctly includes `no4` / `rbo` etc. functions again
> Fix funcs report not generating correctly

- config/splat.us.tt_004.yaml
- include/common.h
- src/servant/tt_004/sword.c
I had thought `D_us_80178670` was a struct of some kind, but addressing only worked as an array of arrays. Unfortunately, there are still other functions which require symbols that cut into these arrays.
The tail of BSS has been moved back into a `bss` segment to support the type declarations the decompiled function want as well as all of the "fake" symbols that the remaining ASM functions want.
> Decompile Sword Familiar's `func_us_80176F28`

- config/splat.us.main.yaml
- src/main/main.c
- src/main/psxsdk/libgpu/font.c
- tools/builds/gen.py
Strongly based off other scratches of FntFlush I found on decomp.me .
Thanks to @sozud for the hint about libgpu which was required to fix the mismatch in https://decomp.me/scratch/WFtbz
> Decompile `main` FntFlush

- src/main/psxsdk/libcd/bios.c
- src/main/psxsdk/libcd/sys.c
All credit goes to @devperson7 : https://decomp.me/scratch/wQ7Dv
I just changed small things to make it fit this project.
Something neat is that `callback` was already decompiled and put at the end of the file, but making it static inline and placing it above `CD_cw` does not cause a mismatch ?? I figure the compiler is generating a non-inline version at the end of the file since it is passed as a function pointer in other functions. Maybe this is happening elsewhere in the project ?
> Decompile `main` CD_cw

- tools/sotn_permuter/permuter_settings.pspeu.toml
- tools/sotn_permuter/permuter_settings.us.toml
I did some limited testing and it appears to function as it did previously for both us and pspeu, but can now handle gte asm macros.
The previous prelude.inc file has been retained in case there are any issues.
> Changed  permuter default prelude file to be include/main.inc
